### PR TITLE
Remove setup_huge_pages function and replace to Hugepage_Setup

### PR DESCRIPTION
**Pull request by v-sijliu**
Part 1 fix of #63 
```
[LISAv2 Test Results Summary]
Test Run On           : 07/22/2019 11:07:07
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1024-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:12

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-COMPLIANCE                                                            PASS                 6.35 
```

### CODE REVIEW

**Review by ader1990 — COMMENTED** [review]
looks good, can you give a run to all the affected TCs?

**Comment by LiliDeng** [comment]
@ader1990 VERIFY-DPDK-OVS abort during execute ./StartOvsSetup.sh, is it known issue? also hit without this change.

```
[LISAv2 Test Results Summary]
Test Run On           : 07/23/2019 05:06:21
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Test Category         : Functional
Test Area             : DPDK
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1024-azure
Total Test Cases      : 9 (7 Passed, 0 Failed, 1 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:2:36

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-COMPLIANCE                                                            PASS                  4.1 
    2 DPDK                 VERIFY-DPDK-RING-LATENCY                                                          PASS                 6.35 
    3 DPDK                 VERIFY-DPDK-OVS                                                                ABORTED                11.84 
    4 DPDK                 VERIFY-DPDK-BUILD-AND-TESTPMD-TEST                                                PASS                18.26 
    5 DPDK                 VERIFY-SRIOV-FAILSAFE-FOR-DPDK                                                    PASS                44.25 
	DPDK-TESTPMD : Initial SRIOV : DPDK 18.11.0 : TxPPS : 15353741 : RxPPS : 15132598 
	DPDK-TESTPMD : Synthetic : DPDK 18.11.0 : TxPPS : 497413 : RxPPS : 0 
	DPDK-TESTPMD : Re-Enable SRIOV : DPDK 18.11.0 : TxPps : 11308123 : RxPps : 11294516 
	DPDK RxPPS : Difference between Initial and Re-Enabled SRIOV : 15132598 : 11294516 : 25.36 % 
    6 DPDK                 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC                                               PASS                13.55 
dpdk_version test_mode phase   fwdrx_pps_avg fwdtx_pps_avg
------------ --------- -----   ------------- -------------
18.11.0      txonly    after   3182423       3182424      
18.11.0      txonly    before  3179282       3179282      
18.11.0      txonly    during  156341        156341       
18.11.0      txonly    overall 2303837       2303837 
    7 DPDK                 VERIFY-DPDK-NFF-GO                                                                PASS                 9.54 
    8 DPDK                 VERIFY-DPDK-VPP                                                                   PASS                16.09 
    9 DPDK                 VERIFY-DPDK-PRIMARY-SECONDARY-PROCESSES                                        SKIPPED                 0.59 

```

**Comment by LiliDeng** [comment]
@ader1990 Could you please review again? Thanks!

**Comment by ader1990** [comment]
@LiliDeng did you run lisav2 with the default DPDK version or with a custom one?

**Comment by ader1990** [comment]
@LiliDeng the 18.11 DPDK version (the default version in LISAv2) is not compatible with the OVS master anymore, that s why it fails. The TC with the latest DPDK version passes.

**Review by ader1990 — APPROVED** [review]

**Pull request merged**
