### PR TITLE
update verify_os_partition_identifier to support CVM

### PR DESCRIPTION
**Pull request by lesscodingmorehappiness**
I misclicked close https://github.com/microsoft/lisa/pull/3223 and have to reopen a new PR 

This one correctly rebased commits with meaningful msg

### CODE REVIEW

**Comment by squirrelsc** [comment]
@lesscodingmorehappiness please continue on the same PR. So it's easy to review changes, and tracking comments. You can reopen a closed PR. Let me try it.

**Comment by squirrelsc** [comment]
> @lesscodingmorehappiness please continue on the same PR. So it's easy to review changes, and tracking comments. You can reopen a closed PR. Let me try it.

It looks not able to reopen, one code changed after closed.

**Comment by squirrelsc** [comment]
@LiliDeng LGTM

**Comment by LiliDeng** [comment]
@lesscodingmorehappiness I tested it on the cvm and non-cvm images, both fail.

**Comment by lesscodingmorehappiness** [comment]
> @lesscodingmorehappiness I tested it on the cvm and non-cvm images, both fail.

I tested with cvm and non-cvm. Pinged you my logs offline.

**Review by LiliDeng — APPROVED** [review]

**Pull request merged**
