### PR TITLE
Fix L3 cache checks on AMD processors

### PR DESCRIPTION
**Pull request by dsrivastavv**

### CODE REVIEW

**Comment by LiliDeng** [comment]
@somil55 Please check on arm64 image. the Model returns 1, maybe a bug?

image

**Comment by dsrivastavv** [comment]
Hi Lili! Definitely seems like a bug. Which image is this?

Regards
Divyansh
________________________________

**Comment by LiliDeng** [comment]
> Hi Lili! Definitely seems like a bug. Which image is this? Regards Divyansh
> […](#)
> ________________________________ From: LiliDeng ***@***.***> Sent: Sunday, January 29, 2023 10:43 PM To: microsoft/lisa ***@***.***> Cc: Divyansh Srivastava ***@***.***>; Mention ***@***.***> Subject: Re: [microsoft/lisa] Fix L3 cache checks on AMD processors (PR #2559) @somil55<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsomil55&data=05%7C01%7Cdivyan%40microsoft.com%7Cf4cbc22039ed4951b60e08db028d54fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638106578272050238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MWRYJBNtnv8dnchxgnTkCZ8hn63MXP5EF%2FEv2XXI1VA%3D&reserved=0> Please check on arm64 image. the Model returns 1, maybe a bug? [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F10083705%2F215406276-1312736e-d95a-4b7d-a95d-c048e62e8089.png&data=05%7C01%7Cdivyan%40microsoft.com%7Cf4cbc22039ed4951b60e08db028d54fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638106578272050238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wCSi%2FlnnV2tddZUqFZQGYnoGiOp0efzXY%2FinAxL901Y%3D&reserved=0> — Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Flisa%2Fpull%2F2559%23issuecomment-1408076135&data=05%7C01%7Cdivyan%40microsoft.com%7Cf4cbc22039ed4951b60e08db028d54fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638106578272050238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BLT1P2O8oD86Na4hoHvfgOZKt7hY2C7ErAcJO8RKWfs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACT4RRMGFRDOKLSAQK3SAGLWU5PJ7ANCNFSM6AAAAAAUJGT22I&data=05%7C01%7Cdivyan%40microsoft.com%7Cf4cbc22039ed4951b60e08db028d54fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638106578272050238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KBpMEjyPHueZpYGUYjSYKsVjy0wvWora0ObWAmm2SPo%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.***>

I used `canonical ubuntuserver 18_04-lts-arm64 18.04.202301100`

**Comment by LiliDeng** [comment]
@somil55 I used `Standard_B2pls_v2` `canonical ubuntuserver 18_04-lts-arm64 18.04.202301100`

**Comment by LiliDeng** [comment]
@somil55 please update code to include match for arm64 cpu model. then we can move forward on this PR.

**Review by LiliDeng — APPROVED** [review]

**Pull request merged**
