### PR TITLE
Add lro change result checkpoint

### PR DESCRIPTION
**Pull request by yuxisun1217**
Signed-off-by: Yuxin Sun <yuxisun@redhat.com>

1. Currently the script only try to change lro but not check the change result. So I add lro change result  check.
2. In Azure this case will **FAIL** because:
```
# ethtool -K eth0 lro on
Cannot change large-receive-offload
Could not change any device features
```
I get such result in RHEL-7.7/RHEL-8/ubuntu-18.04-lts. I'm not sure if this is a bug or by design. If it is by design, we may need to deal with Hyper-V and Azure separately in this script. Which means, check both gro/lro in Hyper-V, and only check gro in Azure.
Thanks!

Before:
```
ethtool version 4.8
Thu Nov 07 09:25:57 2019 : Info: Ethtool is installed!
Thu Nov 07 09:25:57 2019 : Generic-receive-offload is disabled.
Thu Nov 07 09:25:57 2019 : Generic-receive-offload is enabled.
Thu Nov 07 09:25:57 2019 : LRO status:
large-receive-offload: off [fixed]
Thu Nov 07 09:25:57 2019 : Enable large-receive-offload:
Cannot change large-receive-offload
Could not change any device features
Thu Nov 07 09:25:57 2019 : LRO status:
large-receive-offload: off [fixed]
Thu Nov 07 09:25:57 2019 : Disable large-receive-offload:
Cannot change large-receive-offload
```
The test result is PASS.

After:
```
ethtool version 4.8
Thu Nov 07 10:29:59 2019 : Info: Ethtool is installed!
Thu Nov 07 10:29:59 2019 : generic-receive-offload is disabled.
Thu Nov 07 10:29:59 2019 : generic-receive-offload is enabled.
Thu Nov 07 10:29:59 2019 : Cannot enable large-receive-offload.
```
The test result is FAIL

Br,
Yuxin Sun

### CODE REVIEW

**Comment by juhlee-microsoft** [comment]
@yuxisun1217 Thank you for the improvement. Azure does not support LRO change by design. I suggest you should put the condition with platform variable.

**Comment by yuxisun1217** [comment]
Hi @juhlee-microsoft ,

Do you know how to identify Hyper-V and Azure inside shell script? Or shell we separate this case into 2: GRO case for HyperV+Azure and LRO case for Hyper-V only? Thanks!

**Comment by juhlee-microsoft** [comment]
> Hi @juhlee-microsoft ,
> 
> Do you know how to identify Hyper-V and Azure inside shell script? Or shell we separate this case into 2: GRO case for HyperV+Azure and LRO case for Hyper-V only? Thanks!

Please check out the ‘testplatform’ variable. 	[string] $TestPlatform = "",

**Comment by yuxisun1217** [comment]
Hi @juhlee-microsoft ,

Thank you for your reply! But it seems that cannot read "testplatform" or "TestPlatform" in shell script. I read some other cases, it seems that I have to create a .ps1 script, identify the TestPlatform in this .ps1 script, and then use it to run the shell script. Is that correct? Thanks again!

**Comment by juhlee-microsoft** [comment]
> Hi @juhlee-microsoft ,
> 
> Thank you for your reply! But it seems that cannot read "testplatform" or "TestPlatform" in shell script. I read some other cases, it seems that I have to create a .ps1 script, identify the TestPlatform in this .ps1 script, and then use it to run the shell script. Is that correct? Thanks again!

LISAv2 passed some of global or constant values via 'constants.sh' file. As you see below, we could access global variables in PS module easily.
https://github.com/LIS/LISAv2/blob/master/Testscripts/Windows/GPU-TENSORFLOW.ps1#L108

But sometimes we passed those values to Bash shell script like below example.

https://github.com/LIS/LISAv2/blob/master/Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1#L116

Hope this helps.

**Comment by juhlee-microsoft** [comment]
@yuxisun1217 I am just giving you a friendly reminder that PR opens for a long time. If you need more time, please let me know your ETA.

**Comment by yuxisun1217** [comment]
@juhlee-microsoft , thank you for reminding and sorry for late. I was busy on some other stuff these 2 weeks and I'm not quite familiar with powershell and LISAv2 structure so still need several days to finish the powershell script. Do you think it's better to open a new PR when I finished it? Or just keep this PR opened? Thanks!

**Comment by juhlee-microsoft** [comment]
> @juhlee-microsoft , thank you for reminding and sorry for late. I was busy on some other stuff these 2 weeks and I'm not quite familiar with powershell and LISAv2 structure so still need several days to finish the powershell script. Do you think it's better to open a new PR when I finished it? Or just keep this PR opened? Thanks!

I am ok with a few days PR open, @yuxisun1217

**Comment by yuxisun1217** [comment]
Hi @juhlee-microsoft ,
I'm so sorry that I'm still too busy to update this PR these days. I'm closing it now and when I finished it I'll open a new PR then, to prevent keeping this PR opened for too long. Apologize again.

**Pull request closed without merging**
