### PR TITLE
Support passing TestProvider to setup scripts

### PR DESCRIPTION
**Pull request by lizzha**

### CODE REVIEW

**Comment by lizzha** [comment]
This change should not affect existing test. To double confirm, @LiliDeng could you please help to run a test case that has setup script?

**Comment by LiliDeng** [comment]
Test RUNTIME_MEM_HOTADD on HYPERV against this change.

Case definition
```
<testName>RUNTIME_MEM_HOTADD</testName>
<setupScript>.\Testscripts\Windows\RUNTIME-MEM-CONFIGURE.ps1</setupScript>
```

Segment of test log
```
07/12/2019 01:43:23 : [INFO ] Test setup/cleanup started using script:.\Testscripts\Windows\RUNTIME-MEM-CONFIGURE.ps1 with parameters:appGitTag=V0.07.16;startupMem=2GB;testMem=4GB;appGitURL=h
ttps://github.com/ColinIanKing/stress-ng;
```

Test result
```
[LISAv2 Test Results Summary]
Test Run On           : 07/12/2019 01:39:26
VHD Under Test        : \\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\Ubuntu\ubuntu_18.04.1\Ubuntu_18.04.1.vhdx
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:9

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 RUNTIME_MEMORY       RUNTIME_MEM_HOTADD                                                                PASS                 5.87 
```

**Review by LiliDeng — APPROVED** [review]

**Comment by juhlee-microsoft** [comment]
What is it about? It's empty Description.

**Comment by lizzha** [comment]
@juhlee-microsoft , the PR enables setup scripts to call the methods of the test providers

**Pull request merged**
