### PR TITLE
Revert "Ubuntu: fix BVT-CORE-TIMESYNC-NTP install dependencies"

### PR DESCRIPTION
**Pull request by ader1990**
Reverts LIS/LISAv2#67

### CODE REVIEW

**Review by mbivolan — APPROVED** [review]

**Comment by juhlee-microsoft** [comment]
Can you put the reason for the revert this patch?

**Comment by ader1990** [comment]
@juhlee-microsoft  this patch has a change that can impact all the lisav2 tests, more test results are required. @stefanlupsa  please post the test results for all the BVT suire on HyperV.

**Comment by juhlee-microsoft** [comment]
@ader1990 you don't see the LISAv2 failure with this patch actually, right? Are you concerning because there is no test result?

**Comment by ader1990** [comment]
@juhlee-microsoft  this is the main concern change: https://github.com/LIS/LISAv2/pull/71/files#diff-2411aaddd5536a1d954db78a819c3f6fL2102
We need more test results in order to be sure it does not impact all the tests, the method check_exit_status is widely used.

**Comment by juhlee-microsoft** [comment]
understood. @stefanlupsa  please open a new PR with BVT test results.

**Pull request merged**
