### PR TITLE
Fix GPU CUDA|GRID driver test issues in RHEL 8.x

### LINKED ISSUE #349: GPU: skip run on SLES
SLES is not spported for NVIDIA GPU drivers on N-series VM

Ref: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup

### PR DESCRIPTION
**Pull request by Tong-Xu**
Fix https://github.com/LIS/LISAv2/issues/349
Test results:
```
[LISAv2 Test Results Summary]
Test Run On           : 09/03/2019 02:38:55
ARM Image Under Test  : RedHat : RHEL : 8 : Latest
Initial Kernel Version: 4.18.0-80.4.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.4.2.el8_0.x86_64
Total Test Cases      : 1 (0 Passed, 0 Failed, 0 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:0:9

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-CUDA-DRIVER-VALIDATION                                                  SKIPPED                 4.19 
	Using nVidia driver : CUDA 
	Unsupported kernel version! 

[LISAv2 Test Results Summary]
Test Run On           : 09/03/2019 02:39:07
ARM Image Under Test  : RedHat : RHEL : 8 : Latest
Initial Kernel Version: 4.18.0-80.4.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.4.2.el8_0.x86_64
Total Test Cases      : 1 (0 Passed, 0 Failed, 0 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:0:9

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-GRID-DRIVER-VALIDATION                                                  SKIPPED                  4.2 
	Using nVidia driver : GRID 
	Unsupported kernel version! 

[LISAv2 Test Results Summary]
Test Run On           : 09/03/2019 02:39:29
ARM Image Under Test  : OpenLogic : CentOS : 7.5 : Latest
Initial Kernel Version: 3.10.0-862.11.6.el7.x86_64
Final Kernel Version  : 3.10.0-862.11.6.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:22

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-CUDA-DRIVER-VALIDATION                                                     PASS                16.93 
	Using nVidia driver : CUDA 
	lsvmbus: Expected "PCI Express pass-through" count: 1, count inside the VM: 1 : PASS 
	lspci: Expected "3D controller: NVIDIA Corporation" count: 1, found inside the VM: 1 : PASS 
	lshw: Expected Display adapters: 1, total adapters found in VM: 1 : PASS 
	nvidia-smi: Expected GPU count: 1, found inside the VM: 1 : PASS 

[LISAv2 Test Results Summary]
Test Run On           : 09/03/2019 02:40:08
ARM Image Under Test  : RedHat : RHEL : 7.5 : Latest
Initial Kernel Version: 3.10.0-862.34.2.el7.x86_64
Final Kernel Version  : 3.10.0-862.34.2.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:24

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-CUDA-DRIVER-VALIDATION                                                     PASS                19.55 
	Using nVidia driver : CUDA 
	lsvmbus: Expected "PCI Express pass-through" count: 1, count inside the VM: 1 : PASS 
	lspci: Expected "3D controller: NVIDIA Corporation" count: 1, found inside the VM: 1 : PASS 
	lshw: Expected Display adapters: 1, total adapters found in VM: 1 : PASS 
	nvidia-smi: Expected GPU count: 1, found inside the VM: 1 : PASS 
```

### CODE REVIEW

**Comment by juhlee-microsoft** [comment]
The first two results misleading for the user to understand the failure. I expected "$DISTRO not supported. Skip the test." would be the source of the failure. I don't believe "Unsupported kernel version! " will be the right place to make it skip. Can you make me convince? @Tong-Xu

**Comment by Tong-Xu** [comment]
If we don't add these code "Unsupported kernel version!", We will hit issues in this position: https://github.com/LIS/LISAv2/blob/master/Testscripts/Windows/GPU-DRIVER-INSTALL.ps1#L177, 
the test will exit and the result is  Aborted. But at the moment it's not running to the shell script (gpu-driver-install.sh). @juhlee-microsoft

**Comment by juhlee-microsoft** [comment]
> If we don't add these code "Unsupported kernel version!", We will hit issues in this position: https://github.com/LIS/LISAv2/blob/master/Testscripts/Windows/GPU-DRIVER-INSTALL.ps1#L177,
> the test will exit and the result is Aborted. But at the moment it's not running to the shell script (gpu-driver-install.sh). @juhlee-microsoft
You are right. This is why I don't see how the change part got exercised.

**Comment by Tong-Xu** [comment]
@juhlee-microsoft  If the kernel version of redhat_8 supports, the changes in the shell script will be applied at this time. We also commented out the code for installing LIS RPMs and tested it.
The following is the test results:
```
[LISAv2 Test Results Summary]
Test Run On           : 09/05/2019 01:10:34
ARM Image Under Test  : RedHat : RHEL : 8 : Latest
Initial Kernel Version: 4.18.0-80.4.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.4.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:14

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-GRID-DRIVER-VALIDATION                                                     PASS                 9.58 
	Using nVidia driver : GRID 
	lsvmbus: Expected "PCI Express pass-through" count: 1, count inside the VM: 1 : PASS 
	lspci: Expected "3D controller: NVIDIA Corporation" count: 1, found inside the VM: 1 : PASS 
	lshw: Expected Display adapters: 1, total adapters found in VM: 1 : PASS 
	nvidia-smi: Expected GPU count: 1, found inside the VM: 1 : PASS 

[LISAv2 Test Results Summary]
Test Run On           : 09/05/2019 01:12:34
ARM Image Under Test  : RedHat : RHEL : 8 : Latest
Initial Kernel Version: 4.18.0-80.4.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.4.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:14

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-CUDA-DRIVER-VALIDATION                                                  SKIPPED                 4.33 
	Using nVidia driver : CUDA 
```

**Comment by juhlee-microsoft** [comment]
> @juhlee-microsoft If the kernel version of redhat_8 supports, the changes in the shell script will be applied at this time. We also commented out the code for installing LIS RPMs and tested it.
> The following is the test results:
> 
> ```
> [LISAv2 Test Results Summary]
> Test Run On           : 09/05/2019 01:10:34
> ARM Image Under Test  : RedHat : RHEL : 8 : Latest
> Initial Kernel Version: 4.18.0-80.4.2.el8_0.x86_64
> Final Kernel Version  : 4.18.0-80.4.2.el8_0.x86_64
> Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
> Total Time (dd:hh:mm) : 0:0:14
> 
>    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
> -------------------------------------------------------------------------------------------------------------------------------------------
>     1 GPU                  NVIDIA-GRID-DRIVER-VALIDATION                                                     PASS                 9.58 
> 	Using nVidia driver : GRID 
> 	lsvmbus: Expected "PCI Express pass-through" count: 1, count inside the VM: 1 : PASS 
> 	lspci: Expected "3D controller: NVIDIA Corporation" count: 1, found inside the VM: 1 : PASS 
> 	lshw: Expected Display adapters: 1, total adapters found in VM: 1 : PASS 
> 	nvidia-smi: Expected GPU count: 1, found inside the VM: 1 : PASS 
> 
> [LISAv2 Test Results Summary]
> Test Run On           : 09/05/2019 01:12:34
> ARM Image Under Test  : RedHat : RHEL : 8 : Latest
> Initial Kernel Version: 4.18.0-80.4.2.el8_0.x86_64
> Final Kernel Version  : 4.18.0-80.4.2.el8_0.x86_64
> Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
> Total Time (dd:hh:mm) : 0:0:14
> 
>    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
> -------------------------------------------------------------------------------------------------------------------------------------------
>     1 GPU                  NVIDIA-CUDA-DRIVER-VALIDATION                                                  SKIPPED                 4.33 
> 	Using nVidia driver : CUDA 
> ```

Right, this is what I looked for.

**Review by juhlee-microsoft — APPROVED** [review]

**Pull request merged**
