### PR TITLE
Get-Ipv4AndWaitForSSHStart : reduce wait time to get ip

### LINKED ISSUE #177: [P0] Get-IPv4ViaKVP : 8 hours delay in aborting single test
```

05/05/2019 11:51:45 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 11:56:57 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:02:08 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:07:19 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:12:30 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:17:41 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:22:52 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:28:03 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:33:13 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:38:25 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:43:35 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:48:46 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:53:57 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 12:59:08 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:04:19 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:09:30 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:14:41 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:19:52 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:25:03 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:30:14 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:35:25 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:40:36 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:45:47 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:50:58 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 13:56:09 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:01:20 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:06:31 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:11:42 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:16:53 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:22:04 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:27:15 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:32:26 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:37:37 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:42:48 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:47:59 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:53:10 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 14:58:21 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:03:32 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:08:43 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:13:54 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:19:05 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:24:16 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:29:27 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:34:38 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:39:49 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:45:00 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:50:11 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 15:55:22 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:00:33 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:05:44 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:10:55 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:16:06 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:21:17 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:26:28 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:31:39 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:36:50 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:42:01 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:47:12 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:52:23 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 16:57:34 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:02:45 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:07:56 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:13:07 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:18:18 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:23:29 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:28:40 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:33:51 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:39:02 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:44:13 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:49:24 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:54:35 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 17:59:46 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:04:57 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:10:08 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:15:19 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:20:30 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:25:41 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:30:52 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:36:03 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:41:14 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:46:25 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:51:36 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 18:56:47 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:01:58 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:07:09 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:12:20 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:17:31 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:22:42 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:27:53 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:33:04 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:38:15 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:43:26 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:48:37 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:53:48 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 19:58:59 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 20:04:10 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 20:09:21 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 20:14:32 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 20:19:43 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 20:24:54 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0

05/05/2019 20:25:04 : [ERROR] Wait-ForVMToStartKVP: VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0 did not start KVP within timeout period (1000)

05/05/2019 20:25:04 : [ERROR] Get-IPv4AndWaitForSSHStart: Unable to get ipv4 from VM LISAv2-OneVM-centos_7.2_x64-d-284-EW29-636926271935-role-0 via KVP within timeout period (1000)

```

### PR DESCRIPTION
**Pull request by sireeshapotnuru**
Fixes #177 

Reducing StepTimeout to 30 seconds, so the total time to get ip address is limited in 15 minutes.

### CODE REVIEW

**Comment by sireeshapotnuru** [comment]
Test results:

date

Friday, August 16, 2019 2:52:10 AM

PS F:\timeout\LISAv2> Get-IPv4AndWaitForSSHStart -VmName  "sr-rh73" -HvServer "lis-f2324" -Vmport 22 -Password "*****" -User "*****" -StepTimeout 30
08/16/2019 09:57:06 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM sr-rh73

08/16/2019 10:02:08 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM sr-rh73

08/16/2019 10:07:10 : [WARN ] Get-IPv4ViaKVP: No IPv4 address found for VM sr-rh73

08/16/2019 10:07:20 : [ERROR] Wait-ForVMToStartKVP: VM sr-rh73 did not start KVP within timeout period (30)

08/16/2019 10:07:20 : [ERROR] Get-IPv4AndWaitForSSHStart: Unable to get ipv4 from VM sr-rh73 via KVP within timeout period (30)

PS F:\timeout\LISAv2>

[LISAv2 Test Results Summary]

Test Run On           : 08/16/2019 10:38:12
VHD Under Test        : ****\rhel\rhel_7.3\rhel73_x64.vhdx
Test Category         : Functional
Test Area             : KDUMP
Test Priority         : 0,1,2,3
Initial Kernel Version: 3.10.0-514.el7.x86_64
Final Kernel Version  : 3.10.0-514.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:10

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 

-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SINGLE-CORE                                                           PASS                 4.73

**Comment by juhlee-microsoft** [comment]
@johnsongeorge-w Please review and sign-off/comment here, as @iamshital is busy

**Review by iamshital — APPROVED** [review]

**Review by johnsongeorge-w — APPROVED** [review]

**Comment by juhlee-microsoft** [comment]
@sireeshapotnuru 7 files are updated. Can you run all of them with your change and post the test result here?

**Comment by sireeshapotnuru** [comment]
> @sireeshapotnuru 7 files are updated. Can you run all of them with your change and post the test result here?

@juhlee-microsoft  please find the test results as below

LISAv2 Test Results Summary]
Test Run On           : 08/22/2019 06:41:45
VHD Under Test        : ****\rhel\rhel_7.3\rhel73_x64.vhdx
Test Category         : Functional
Test Area             : KDUMP
Test Priority         : 0,1,2,3
Initial Kernel Version: 3.10.0-514.el7.x86_64
Final Kernel Version  : 3.10.0-514.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:10

ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 

-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SINGLE-CORE                                                           PASS                 4.48 


[LISAv2 Test Results Summary]
Test Run On           : 08/22/2019 06:52:32
VHD Under Test        : ****\rhel\rhel_7.4\RHEL74_ga_gen1.vhdx
Test Category         : Functional
Test Area             : CORE
Test Priority         : 0,1,2,3
Initial Kernel Version: 3.10.0-693.el7.x86_64
Final Kernel Version  : 3.10.0-693.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:8
   
ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 

-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 MAX-VCPU                                                                          PASS                 2.34 


[LISAv2 Test Results Summary]
Test Run On           : 08/22/2019 07:01:21
VHD Under Test        : ****\rhel\rhel_7.4\RHEL74_ga_gen1.vhdx
Test Category         : Functional
Test Area             : PROD_CHECKPOINT
Test Priority         : 0,1,2,3
Initial Kernel Version: 3.10.0-693.el7.x86_64
Final Kernel Version  : 3.10.0-693.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:9

ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 

-------------------------------------------------------------------------------------------------------------------------------------------
    1 PROD_CHECKPOINT      PRODUCTION-CHECKPOINT-3CHAIN-VHD                                                  PASS                  3.5 

[LISAv2 Test Results Summary]
Test Run On           : 08/22/2019 07:11:07
VHD Under Test        : ****\rhel\rhel_7.4\RHEL74_ga_gen1.vhdx
Test Category         : Functional
Test Area             : STORAGE
Test Priority         : 0,1,2,3
Initial Kernel Version: 3.10.0-693.el7.x86_64
Final Kernel Version  : 3.10.0-693.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:7
   
ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 

-------------------------------------------------------------------------------------------------------------------------------------------
    1 STORAGE              STORAGE-TAKE-REVERT-SNAPSHOT                                                      PASS                 2.63

[LISAv2 Test Results Summary]
Test Run On           : 08/22/2019 07:17:41
VHD Under Test        : \\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\RHEL\rhel_7.4\RHEL74_ga_gen1.vhdx
Initial Kernel Version: 3.10.0-693.el7.x86_64
Final Kernel Version  : 3.10.0-693.el7.x86_64
Total Test Cases      : 1 (0 Passed, 1 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:9

  
ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 

-------------------------------------------------------------------------------------------------------------------------------------------
    1 SRIOV                SRIOV-REBOOT-VM                                                                   FAIL                 6.77 

[LISAv2 Test Results Summary]
Test Run On           : 08/22/2019 10:01:23
VHD Under Test        : \\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\RHEL\RHEL_7.3\rhel73_x64.vhdx
Initial Kernel Version: 3.10.0-514.el7.x86_64
Total Test Cases      : 1 (0 Passed, 1 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:33

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 STRESS               STRESSTEST-CHANGE-MTU-RELOAD-NETVSC                                               FAIL                31.14 

[LISAv2 Test Results Summary]
Test Run On           : 08/22/2019 07:57:39
VHD Under Test        : ****\rhel\rhel_7.4\RHEL74_ga_gen1.vhdx
Test Category         : Functional
Test Area             : CORE
Test Priority         : 0,1,2,3
Initial Kernel Version: 3.10.0-693.el7.x86_64
Final Kernel Version  : 3.10.0-693.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:7
   
ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 

-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 REBOOT-DIFFERENT-MEMORY-SETTINGS                                                  PASS                 2.38


Tests STRESSTEST-CHANGE-MTU-RELOAD-NETVSC, SRIOV-REBOOT-VM are failed even with master, so they are not related to this PR changes

**Pull request merged**
