### PR TITLE
azure extension: add delete, check_exist and list_all methods

### PR DESCRIPTION
**Pull request by LiliDeng**

### CODE REVIEW

**Comment by squirrelsc** [comment]
@narrieta This PR supports more extension operations like list, delete, exists. Do you have a chance to try? Thank you.

**Comment by narrieta** [comment]
@squirrelsc our automation does not use the LISA feature, so I have no way to try it. Maybe you can modify https://github.com/microsoft/lisa/blob/main/microsoft/testsuites/vm_extensions/waagent.py and run it on your side?

**Comment by squirrelsc** [comment]
> @squirrelsc our automation does not use the LISA feature, so I have no way to try it. Maybe you can modify https://github.com/microsoft/lisa/blob/main/microsoft/testsuites/vm_extensions/waagent.py and run it on your side?

I see. I will get this PR merged first.

**Review by squirrelsc — APPROVED** [review]

**Comment by LiliDeng** [comment]
> > @squirrelsc our automation does not use the LISA feature, so I have no way to try it. Maybe you can modify https://github.com/microsoft/lisa/blob/main/microsoft/testsuites/vm_extensions/waagent.py and run it on your side?
> 
> I see. I will get this PR merged first.

I have tried it by updating code in verify_vm_agent locally.

**Pull request merged**
