### PR TITLE
Azure: Dynamic mapping of Azure VM size to their family

### LINKED ISSUE #216: Need to update regex of VM family section for M_v2
New VM size, Mv2 released but the LISAv2 code has missing regex for Mv2.

https://github.com/LIS/LISAv2/blob/master/Libraries/Azure.psm1#L128

### PR DESCRIPTION
**Pull request by iamshital**
This pull request addresses the issue of manual mapping of Azure VM sizes to their families.
**Now, the VM family will be detected automatically using the data obtained from Azure.**

Fixes #216

### CODE REVIEW

**Comment by iamshital** [comment]
Affected code in action
---------------------------
```
05/15/2019 14:40:21 : [INFO ] Starting the test
05/15/2019 14:40:22 : [INFO ] VERIFY-DEPLOYMENT-PROVISION started running.
05/15/2019 14:40:22 : [INFO ] Current test setup: OneVM
05/15/2019 14:40:22 : [INFO ] Checking the subscription usage...
05/15/2019 14:40:22 : [INFO ] Getting Azure 'ComputeSKU' details...
05/15/2019 14:40:33 : [INFO ] Estimating VM #1 usage.
05/15/2019 14:40:34 : [INFO ]   Current Regional Cores usage : 2851 cores. Requested:1. Estimated usage=2852. Max Allowed cores:5620/5620
05/15/2019 14:40:34 : [INFO ]   Current standardDSv2Family usage : 1019 cores. Requested:1. Estimated usage=1020. Max Allowed cores:1024/1024
05/15/2019 14:40:36 : [INFO ] Current 'Resource Group' usage:210. Requested:1. Estimated usage:211. Maximum allowed:980/980.
05/15/2019 14:40:38 : [INFO ] Current 'Storage Account' usage:3. Requested:1. Estimated usage:4. Maximum allowed:250/250.
05/15/2019 14:40:40 : [INFO ] Current 'Public IP' usage:90. Requested:1. Estimated usage:91. Maximum allowed:1000/1000.
05/15/2019 14:40:40 : [INFO ] Current 'Virtual Network' usage:90. Requested:1. Estimated usage:91. Maximum allowed:1000/1000.
05/15/2019 14:40:40 : [INFO ] Current 'Network Security Group' usage:2. Requested:1. Estimated usage:3. Maximum allowed:5000/5000.
05/15/2019 14:40:40 : [INFO ] Current 'Load Balancer' usage:89. Requested:1. Estimated usage:90. Maximum allowed:1000/1000.
05/15/2019 14:40:40 : [INFO ] Estimated subscription usage is under allowed limits.
```

**Comment by lizzha** [comment]
It needs fully test for different size families

**Comment by iamshital** [comment]
> It needs fully test for different size families

I've verified that VM family is accurately detected. But still I'll run test with at least one VM size in each VM size family.

**Comment by juhlee-microsoft** [comment]
I am ok with this change. Look forward to the result.

**Comment by iamshital** [comment]
Verified "VERIFY-DEPLOYMENT-PROVISION" test with below size families -
--------------------------


Size Family | Is Size family detected correctly? | Test Result
-- | -- | --
standardA0_A7Family | Yes | PASS
standardDSv2Family | Yes | PASS
standardDv2Family | Yes | PASS
standardEv3Family | Yes | PASS
standardFFamily | Yes | PASS
standardFSFamily | Yes | PASS
standardGFamily | Yes | PASS
standardHFamily | Yes | PASS
standardLSv2Family | Yes | PASS
standardNCFamily | Yes | PASS
standardNVFamily | Yes | PASS
standardNVSv2Family | Yes | PASS
standardMSv2Family | Yes | PASS

**Review by juhlee-microsoft — APPROVED** [review]

**Pull request merged**
