### PR TITLE
PartitionDisks.sh: Skip the OS disk

### PR DESCRIPTION
**Pull request by xian123**
If there are multiple disk controllers, the os disk name may change after reboot the VM.

### CODE REVIEW

**Comment by chvalean** [comment]
I was expecting non sda devices to swap - like sdb <-> sdc, but not sda itself.
Are you sure from your test observation that that's happening?

**Comment by xian123** [comment]
Yes, it happens.  The sda device may swap to other devices.  If you test PRODUCTION-CHECKPOINT-IDE_SCSI case for many times, you'll 100% hit the issue.

**Review by juhlee-microsoft — APPROVED** [review]

**Comment by xian123** [comment]
In the PRODUCTION-CHECKPOINT-PARTITION.ps1, the hard code device names like "/dev/sdd1" and "/dev/sdc1" are used. They may have the same issue that the OS disk swaps to sdd/sdc.

**Comment by juhlee-microsoft** [comment]
@xian123 please resolve the conflict. Let me merge it.

**Review by chvalean — APPROVED** [review]

**Comment by chvalean** [comment]
@LiliDeng please merge this after you verify with @xian123 , confused about the PR labels if this is safe to merge.
I resolved the merge conflict.

**Pull request merged**
