### PR TITLE
Add a new RAID0 disk test

### PR DESCRIPTION
**Pull request by juhlee-microsoft**
LISAv2 has one test case called PERF-STORAGE-4K-IO. This test runs over 12-disk RAID0. The average customer setup has 24 or higher number of disks for RAID0 configuration. Tried 48 and 36-disk, but a new raid disk failed with fio libaio engine. So increased the disk count from 12 to 24 for new test. Reduced the maxQDepth from 256 to 64, increased the waiting time for bigger RAID size, and decreased the number of job from the feedback.

[LISAv2 Test Results Summary]
Test Run On           : 10/12/2020 23:43:19
ARM Image Under Test  : RedHat : RHEL : 8.2 : latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:2:30

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 STORAGE              PERF-STORAGE-DISK-IO                                                              PASS               143.07
      ARMImageName: RedHat RHEL 8.2 latest, StorageAccountType: Premium_LRS, TestLocation: westus2, Kernel Version: 4.18.0-193.14.3.el8_2.x86_64
      Mode=randread : block_size=4K q_depth=1 iops=404.958650
      Mode=randread : block_size=4K q_depth=2 iops=955.830147
      Mode=randread : block_size=4K q_depth=4 iops=1922.450258
      Mode=randread : block_size=4K q_depth=8 iops=2807.855255
      Mode=randread : block_size=4K q_depth=16 iops=5107.883071
      Mode=randread : block_size=4K q_depth=32 iops=5108.259534
      Mode=randread : block_size=4K q_depth=64 iops=5108.292833
      Mode=randwrite : block_size=4K q_depth=1 iops=548.121506
      Mode=randwrite : block_size=4K q_depth=2 iops=1133.485777
      Mode=randwrite : block_size=4K q_depth=4 iops=2279.839067
      Mode=randwrite : block_size=4K q_depth=8 iops=4188.019062
      Mode=randwrite : block_size=4K q_depth=16 iops=5108.265016
      Mode=randwrite : block_size=4K q_depth=32 iops=5108.050610
      Mode=randwrite : block_size=4K q_depth=64 iops=4994.718025
      Mode=read : block_size=4K q_depth=1 iops=468.635105
      Mode=read : block_size=4K q_depth=2 iops=988.683409
      Mode=read : block_size=4K q_depth=4 iops=1979.603401
      Mode=read : block_size=4K q_depth=8 iops=2771.326906
      Mode=read : block_size=4K q_depth=16 iops=5108.081689
      Mode=read : block_size=4K q_depth=32 iops=5108.049109
      Mode=read : block_size=4K q_depth=64 iops=5108.420528
      Mode=write : block_size=4K q_depth=1 iops=591.416057
      Mode=write : block_size=4K q_depth=2 iops=1073.116423
      Mode=write : block_size=4K q_depth=4 iops=2303.092323
      Mode=write : block_size=4K q_depth=8 iops=4694.420877
      Mode=write : block_size=4K q_depth=16 iops=5108.810200
      Mode=write : block_size=4K q_depth=32 iops=5108.312615
      Mode=write : block_size=4K q_depth=64 iops=5108.077118

[LISAv2 Test Results Summary]
Test Run On           : 10/13/2020 21:48:36
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:2:28

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 STORAGE              PERF-STORAGE-DISK-IO                                                              PASS               143.12
      ARMImageName: Canonical UbuntuServer 18.04-LTS latest, StorageAccountType: Premium_LRS, TestLocation: westus2, Kernel Version: 5.4.0-1026-azure
      Mode=randread : block_size=4K q_depth=1 iops=538.446410
      Mode=randread : block_size=4K q_depth=2 iops=1135.899094
      Mode=randread : block_size=4K q_depth=4 iops=2261.265360
      Mode=randread : block_size=4K q_depth=8 iops=2970.103632
      Mode=randread : block_size=4K q_depth=16 iops=5107.967400
      Mode=randread : block_size=4K q_depth=32 iops=5108.033740
      Mode=randread : block_size=4K q_depth=64 iops=5107.967168
      Mode=randwrite : block_size=4K q_depth=1 iops=555.788147
      Mode=randwrite : block_size=4K q_depth=2 iops=1157.792281
      Mode=randwrite : block_size=4K q_depth=4 iops=2317.111750
      Mode=randwrite : block_size=4K q_depth=8 iops=4792.051386
      Mode=randwrite : block_size=4K q_depth=16 iops=5107.957065
      Mode=randwrite : block_size=4K q_depth=32 iops=5108.056290
      Mode=randwrite : block_size=4K q_depth=64 iops=5108.744655
      Mode=read : block_size=4K q_depth=1 iops=480.268399
      Mode=read : block_size=4K q_depth=2 iops=970.026866
      Mode=read : block_size=4K q_depth=4 iops=2075.502932
      Mode=read : block_size=4K q_depth=8 iops=2575.075209
      Mode=read : block_size=4K q_depth=16 iops=5107.992254
      Mode=read : block_size=4K q_depth=32 iops=5107.789554
      Mode=read : block_size=4K q_depth=64 iops=5108.491966
      Mode=write : block_size=4K q_depth=1 iops=571.319525
      Mode=write : block_size=4K q_depth=2 iops=1183.952107
      Mode=write : block_size=4K q_depth=4 iops=2412.940581
      Mode=write : block_size=4K q_depth=8 iops=4577.279485
      Mode=write : block_size=4K q_depth=16 iops=5108.459277
      Mode=write : block_size=4K q_depth=32 iops=5108.774083
      Mode=write : block_size=4K q_depth=64 iops=5108.515220

### CODE REVIEW

**Comment by LiliDeng** [comment]
Why we need this, any requirement from dev? Or it is used to cover ICM?

**Comment by juhlee-microsoft** [comment]
> Why we need this, any requirement from dev? Or it is used to cover ICM?

I hope you remember about my big size VM research output. Discussed the topics in the team's meeting.

**Comment by LiliDeng** [comment]
> > Why we need this, any requirement from dev? Or it is used to cover ICM?
> 
> I hope you remember about my big size VM research output. Discussed the topics in the team's meeting.

Sorry, I miss some context.

**Comment by juhlee-microsoft** [comment]
> > > Why we need this, any requirement from dev? Or it is used to cover ICM?
> > 
> > 
> > I hope you remember about my big size VM research output. Discussed the topics in the team's meeting.
> 
> Sorry, I miss some context.

This is what we discussed a month ago after my big VM research. I created about 20+ work items, and this is one of them. This is for customer scenario friendly test setup. Can you review it?

**Review by abhimarathe — APPROVED** [review]

**Pull request merged**
