### PR TITLE
Refine testsetup and cleanup for azure platform.

### PR DESCRIPTION
**Pull request by harz566**
1. TestCase can define `<CleanupScript>` for itself to do cleanup/reset job and make it ready for the next TestCase to be run from the same setup group.
2. use the optional parameter '-ReuseVmOnFailure' to speedup your tests:  when there's a test case aborted/failed due to some reason, but user wants to reuse the VM instances for the next test case in queue, and get rid of the time cost for a new deployment (which is time consuming).    When the last aborted/failed test case cleanup script is finished (Test case will make sure it's fully cleanup/reset to an intial state for next test case), this '-ReuseVmOnFailure' option will restart VM instances and making sure it's VM-Alive, after that it will run the next test case as usual.   If the Restarting VM failed or VMInstance is not VM-Alive,  LISA will delete the VM resource and start another new deployment (which is current default behavior)
3.  To make backward compatible, as Azure Test Cases will not run `<CleanupScript>` before, only HyperV test cases will run CleanupScripts, so, just return for Azure TestPlatform from those existing cleanup scripts which have been used in the shared test casess (both targets for Azure and HyperV)

@yuxisun1217  Please take a look whether it address your requirement.  As @LiliDeng  commented, creating VM snapshot or backup is time consuming for most scenarios.  if we could not do cleanup/reset the VM by some cleanup scripts,  then deploy another VM in a new resource group (or -UseExistingRG) should be much more efficient than taking a snapshort/backup of VM, and restore the VM to original state for the next test case in queue.

==============Test Log =========================
. 'C:\LISAv2\Run-LisaV2.ps1' -TestPlatform 'Azure' -RGIdentifier 'test-1m' -ARMImageName 'Canonical UbuntuServer 18.04-LTS Latest' -OverrideVMSize 'Standard_DS1_v2' -XMLSecretFile 'xyz.xml' -TestNames 'LSVMBUS,NVIDIA-CUDA-DRIVER-VALIDATION-MAX-GPU,VERIFY-DEPLOYMENT-PROVISION' -ResourceCleanup 'Delete' -ForceCustom -ReuseVMOnFailure

**I make the first test case aborted on purpose, and let LISA ReuseVmOnFailure, all following test cases get passed, with only one VM instance via one deployment in total.**

07/16/2020 05:36:21 : [INFO ] Prepare test log structure and start testing now ...
07/16/2020 05:36:21 : [INFO ] (1/3) testing started: NVIDIA-CUDA-DRIVER-VALIDATION-MAX-GPU
07/16/2020 05:36:21 : [INFO ] SetupConfig: { ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM }
07/16/2020 05:36:21 : [INFO ] Deploy target machine for test if required 
...
07/16/2020 05:39:54 : [INFO ] End of testing: NVIDIA-CUDA-DRIVER-VALIDATION-MAX-GPU with SetupConfig: { ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM, TestLocation: westus2 }, **result: ABORTED**
07/16/2020 05:39:54 : [INFO ] PASS    - 0
07/16/2020 05:39:54 : [INFO ] SKIPPED - 0
07/16/2020 05:39:54 : [INFO ] FAIL    - 0
07/16/2020 05:39:55 : [INFO ] ABORTED - 1
07/16/2020 05:39:55 : [INFO ] PENDING - 2 

**07/16/2020 05:39:55 : [INFO ] Keep deployed target machine for future reuse, as '-ReuseVmOnFailure' is True
07/16/2020 05:39:56 : [INFO ] Restarting LISAv2-OneVM-test-1m-CA48-20200715223632-role-0 from shell...**

07/16/2020 05:40:05 : [INFO ] Restart-VMFromShell executes successfully.
07/16/2020 05:40:07 : [INFO ] Trying to connect to deployed VMs.
07/16/2020 05:40:28 : [WARN ] TCP test failed
07/16/2020 05:40:28 : [INFO ] Connecting to 52.229.13.145 : 22 failed.
07/16/2020 05:40:28 : [INFO ] 1 VM(s) still waiting for port 22 open.
07/16/2020 05:40:28 : [INFO ] Retrying 1/50 in 3 seconds.
07/16/2020 05:40:31 : [INFO ] Connecting to 52.229.13.145 : 22 succeeded.
07/16/2020 05:40:31 : [INFO ] The SSH ports for all VMs are open.
07/16/2020 05:40:31 : [INFO ] (2/3) testing started: VERIFY-DEPLOYMENT-PROVISION
07/16/2020 05:40:31 : [INFO ] SetupConfig: { ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM }
07/16/2020 05:40:31 : [INFO ] Run test case against the target machine ...
07/16/2020 05:40:31 : [INFO ] ==> Run test setup script if defined.
07/16/2020 05:40:31 : [INFO ] ==> Check the target machine kernel log.
07/16/2020 05:40:31 : [INFO ] Collecting LISAv2-OneVM-test-1m-CA48-20200715223632-role-0 VM Kernel Initial Logs 
...

07/16/2020 05:42:48 : [INFO ] All files removed from current user lisa home folder successfully. VM IP : 52.229.13.145 PORT : 22
07/16/2020 05:42:49 : [INFO ] End of testing: VERIFY-DEPLOYMENT-PROVISION with SetupConfig: { ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM, TestLocation: westus2 }, **result: PASS**
07/16/2020 05:42:49 : [INFO ] PASS    - 1
07/16/2020 05:42:49 : [INFO ] SKIPPED - 0
07/16/2020 05:42:49 : [INFO ] FAIL    - 0
07/16/2020 05:42:49 : [INFO ] ABORTED - 1
07/16/2020 05:42:49 : [INFO ] PENDING - 1 

07/16/2020 05:42:49 : [INFO ] (3/3) testing started: LSVMBUS
07/16/2020 05:42:49 : [INFO ] SetupConfig: { ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM }
07/16/2020 05:42:49 : [INFO ] Run test case against the target machine ...
07/16/2020 05:42:49 : [INFO ] ==> Run test setup script if defined.
07/16/2020 05:42:49 : [INFO ] ==> Check the target machine kernel log.
07/16/2020 05:42:49 : [INFO ] Collecting LISAv2-OneVM-test-1m-CA48-20200715223632-role-0 VM Kernel Initial Logs 
...

07/16/2020 05:43:24 : [INFO ] All files removed from current user lisa home folder successfully. VM IP : 52.229.13.145 PORT : 22
07/16/2020 05:43:24 : [INFO ] End of testing: LSVMBUS with SetupConfig: { ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM, TestLocation: westus2 }, result: PASS
07/16/2020 05:43:24 : [INFO ] PASS    - 2
07/16/2020 05:43:24 : [INFO ] SKIPPED - 0
07/16/2020 05:43:24 : [INFO ] FAIL    - 0
07/16/2020 05:43:24 : [INFO ] ABORTED - 1
07/16/2020 05:43:24 : [INFO ] PENDING - 0 

07/16/2020 05:43:25 : [INFO ] Delete deployed target machine 
...
07/16/2020 05:43:33 : [INFO ] Test CA48 finished
07/16/2020 05:43:33 : [INFO ] 
[LISAv2 Test Results Summary]
Test Run On           : 07/16/2020 05:36:21
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : Latest
Override VM size Under Test  : Standard_DS1_v2
Initial Kernel Version: 5.3.0-1032-azure
Final Kernel Version  : 5.3.0-1032-azure
Total Test Cases      : 3 (2 Passed, 0 Failed, 1 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:7

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-CUDA-DRIVER-VALIDATION-MAX-GPU                                          ABORTED                 1.12 
      ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM, TestLocation: westus2
    2 CORE                 VERIFY-DEPLOYMENT-PROVISION                                                       PASS                 2.29 
      ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM, TestLocation: westus2
      FirstBoot : PASS
      FirstBoot : Call Trace Verification : PASS
      Reboot : PASS
      Reboot : Call Trace Verification : PASS
      
    3 CORE                 LSVMBUS                                                                           PASS                 0.59 
      ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, OverrideVMSize: Standard_DS1_v2, SetupType: OneVM, TestLocation: westus2

Logs can be found at C:\LISAv2\TestResults\2020-07-15-22-34-32-0293

07/16/2020 05:43:33 : [DEBUG] Creating 'C:\LISAv2\Azure-CA48-TestLogs.zip' from 'C:\LISAv2\TestResults\2020-07-15-22-34-32-0293'
07/16/2020 05:43:33 : [DEBUG] C:\LISAv2\Azure-CA48-TestLogs.zip created successfully.
07/16/2020 05:43:33 : [INFO ] Analyzing test results ...
07/16/2020 05:43:33 : [INFO ] LISAv2 exit code: 1

### CODE REVIEW

**Comment by harz566** [comment]
@yuxisun1217  you need define (or reuse) your own cleanup scripts for your test cases.
Create VM snapshot or backup is time consuming for most scenarios.  if we could not do cleanup/reset the VM by some cleanup scripts,  deploy another VM in a new resource group (or -UseExistingRG) should be easy than taking a snapshort/backup of VM, then restore for the next test case in queue.

**Comment by LiliDeng** [comment]
@yuxisun1217 Let know if this approach meet your scenario.

**Comment by yuxisun1217** [comment]
Hi @LiliDeng @harz566 ,

Sorry for late. I just did a general verification that added the <CleanupScript> param in a case with a script like "RestartVM.ps1" and it worked well. It's just what I needed. As Lili said that usually I should recover the VM in the case. But I think that in some special cases maybe restart or delete the VM is a easier choice. Also, with this cleanup phase we can make the case steps focus on the checkpoints and use some common recovery scripts to recover the VM. 

One question is that do we consider to also add it to Ready provider?

Thank you so much for adding this feature!

**Comment by harz566** [comment]
> Hi @LiliDeng @harz566 ,
> 
> Sorry for late. I just did a general verification that added the param in a case with a script like "RestartVM.ps1" and it worked well. It's just what I needed. As Lili said that usually I should recover the VM in the case. But I think that in some special cases maybe restart or delete the VM is a easier choice. Also, with this cleanup phase we can make the case steps focus on the checkpoints and use some common recovery scripts to recover the VM.
> 
> One question is that do we consider to also add it to Ready provider?
> 
> Thank you so much for adding this feature!

@yuxisun1217 Ready already has it.

**Review by LiliDeng — APPROVED** [review]

**Pull request merged**
