### PR TITLE
Remove Infiniband on_before_deploy

### PR DESCRIPTION
**Pull request by kamalca**
Availability sets are an optimization not a requirement and it is causing problems for Ultra Disk and Availability Feature.

### CODE REVIEW

**Comment by squirrelsc** [comment]
@LiliDeng LGTM

**Comment by LiliDeng** [comment]
@kamalca when we don't set available set in the runbook and run a RDMA case, I saw below issue
```
InfinibandSuite.verify_ping_pong: FAILED   
deployment failed. LisaException: InvalidParameter: Required parameter 'platformFaultDomainCount' is missing (null).
```

**Comment by kamalca** [comment]
> @kamalca when we don't set available set in the runbook and run a RDMA case, I saw below issue
> 
> ```
> InfinibandSuite.verify_ping_pong: FAILED   
> deployment failed. LisaException: InvalidParameter: Required parameter 'platformFaultDomainCount' is missing (null).
> ```

When was this run? I added a test requirement three days ago.

**Comment by kamalca** [comment]
> @kamalca when we don't set available set in the runbook and run a RDMA case, I saw below issue
> 
> ```
> InfinibandSuite.verify_ping_pong: FAILED   
> deployment failed. LisaException: InvalidParameter: Required parameter 'platformFaultDomainCount' is missing (null).
> ```

I have added a safety check to set a default value for `platformFaultDomainCount` and `platformUpdateDomainCount` if they are not defined.

**Comment by LiliDeng** [comment]
> @LiliDeng LGTM

@squirrelsc could you please review the updated code, thanks.

**Comment by squirrelsc** [comment]
@LiliDeng LGTM.

**Review by LiliDeng — APPROVED** [review]

**Pull request merged**
