### PR TITLE
fix issue in dpdk-utils.sh

### PR DESCRIPTION
**Pull request by v-sijliu**
After fix: create /root/dpdk path and install dpdk success.

### CODE REVIEW

**Comment by LiliDeng** [comment]
@abhimarathe Hi, could you please let know why you change this, we found it break some cases like VERIFY-DPDK-RING-LATENCY

**Comment by abhimarathe** [comment]
@LiliDeng  I added this change as new releases contain their version numbers in the path. So this would make one path for all the releases. I'll check why VERIFY-DPDK-RING-LATENCY is breaking. Could you please share some more details?

**Comment by juhlee-microsoft** [comment]
> @LiliDeng I added this change as new releases contain their version numbers in the path. So this would make one path for all the releases. I'll check why VERIFY-DPDK-RING-LATENCY is breaking. Could you please share some more details?

@abhimarathe can you try to run all DPDK tests including VERIFY-DPDK-RING-LATENCY in your branch? @LiliDeng reported your change broke the existing test. It looks you should verify your change with different dpdk package options.

**Comment by abhimarathe** [comment]
> > @LiliDeng I added this change as new releases contain their version numbers in the path. So this would make one path for all the releases. I'll check why VERIFY-DPDK-RING-LATENCY is breaking. Could you please share some more details?
> 
> @abhimarathe can you try to run all DPDK tests including VERIFY-DPDK-RING-LATENCY in your branch? @LiliDeng reported your change broke the existing test.

Sure. I just wanted to know in which cases that break was found, so that I can optimize repro.
 I will run all the scenarios after the fix.

**Comment by LiliDeng** [comment]
@abhimarathe 
VERIFY-DPDK-BUILD-AND-TESTPMD-TEST
VERIFY-SRIOV-FAILSAFE-FOR-DPDK

**Comment by LiliDeng** [comment]
Included in #531

**Pull request closed without merging**
