### PR TITLE
Added "VMGeneration" to Teletemetry DB

### PR DESCRIPTION
**Pull request by iamshital**
This PR adds a column to Telemetry Database - "VMGenaration".
This gives us more flexibility to create PowerBI reports / Charts / Sheets in automated way.

- [x] Verified on Azure
- [x] Verified on HyperV
- [x] Verified database push
- [ ] Update the Telemetry Database after the PR is merged

### CODE REVIEW

**Review by juhlee-microsoft — COMMENTED** [review]
Please post the test result.

**Comment by iamshital** [comment]
Execution is verified
-------------------------------
```
03/11/2019 10:55:03 : [INFO ] Get the SQL query of test results:  done
03/11/2019 10:55:03 : [INFO ] SQLQuery:  INSERT INTO LISAv2Results_Test (DateTimeUTC,TestPlatform,TestLocation,TestCategory,TestArea,TestName,TestResult,SubTestName,SubTestResult,ExecutionTag,GuestDistro,KernelVersion,LISVersion,HostVersion,VMSize,VMGeneration,Networking,ARMImage,OsVHD,LogFile,BuildURL) VALUES ('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','','','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','1','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','FirstBoot','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','1','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','FirstBoot : Call Trace Verification','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','1','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','Reboot','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','1','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','Reboot : Call Trace Verification','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','1','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', '')
03/11/2019 10:55:03 : [INFO ] Uploading test results to database :  done!!
03/11/2019 10:55:03 : [INFO ] Start to do clean up for case BVT-VERIFY-DEPLOYMENT-PROVISION
03/11/2019 10:55:03 : [INFO ] Removing all files logs from IP : xx.xx.xx.xx PORT : 22
03/11/2019 10:55:03 : [INFO ] Uploading C:\GitHub\LISAv2-2\TestResults\2019-11-03-03-51-06-1411\BVT-VERIFY-DEPLOYMENT-PROVISION\runtest.sh to lisa : xx.xx.xx.xx, port 22 using Password authentication
03/11/2019 10:55:05 : [INFO ] Upload successful after 1 attempt
03/11/2019 10:55:05 : [INFO ] .\Tools\plink.exe -t -pw ****** -P 22 lisa@xx.xx.xx.xx "echo ****** | sudo -S rm -rf *"
03/11/2019 10:55:06 : [INFO ] rm -rf * executed successfully in 1.14 seconds.
03/11/2019 10:55:06 : [INFO ] All files removed from /home/lisa successfully. VM IP : xx.xx.xx.xx PORT : 22
03/11/2019 10:55:06 : [INFO ] CURRENT - PASS    - 1
03/11/2019 10:55:06 : [INFO ] CURRENT - SKIPPED - 0
03/11/2019 10:55:06 : [INFO ] CURRENT - FAIL    - 0
03/11/2019 10:55:06 : [INFO ] CURRENT - ABORTED - 0
03/11/2019 10:55:06 : [INFO ] BVT-VERIFY-DEPLOYMENT-PROVISION ended running with status: PASS.
03/11/2019 10:55:06 : [INFO ] Checking if Hyper-V VM group 'LISAv2-OneVM-SS-TH60-636878730738' exists on LIS-F2325...
03/11/2019 10:55:06 : [INFO ] Stop-VM -Name LISAv2-OneVM-SS-TH60-636878730738-role-0 -Force -TurnOff
03/11/2019 10:55:08 : [INFO ] VHD C:\GitHub\LISAv2-2\VHDs_Destination_Path\LISAv2-OneVM-SS-TH60-636878730738-role-0-diff-OSDisk_00EE81DF-31D7-4C03-AC03-C03EA319CFD7.avhdx removed!
03/11/2019 10:55:08 : [INFO ] VHD C:\GitHub\LISAv2-2\VHDs_Destination_Path\LISAv2-OneVM-SS-TH60-636878730738-role-0-diff-OSDisk.vhdx removed!
03/11/2019 10:55:09 : [INFO ] VHD C:\Users\v-prmhet\AppData\Local\Temp\ResourceDisk-636878730837850118-sdb_927508A6-10D2-44E9-869E-3BAB40267255.avhdx removed!
03/11/2019 10:55:09 : [INFO ] VHD C:\Users\v-prmhet\AppData\Local\Temp\ResourceDisk-636878730837850118-sdb.vhdx removed!
03/11/2019 10:55:10 : [INFO ] Hyper-V VM LISAv2-OneVM-SS-TH60-636878730738-role-0 removed!
03/11/2019 10:55:10 : [INFO ] Hyper-V VM group LISAv2-OneVM-SS-TH60-636878730738 removed!
03/11/2019 10:55:10 : [INFO ] Successfully delete HyperV group LISAv2-OneVM-SS-TH60-636878730738.
03/11/2019 10:55:10 : [INFO ] Test TH60 finished
03/11/2019 10:55:10 : [INFO ]
[LISAv2 Test Results Summary]
Test Run On           : 03/11/2019 10:51:13
VHD Under Test        : \\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:3

   ID TestCaseName                                                                TestResult TestDuration(in minutes)
---------------------------------------------------------------------------------------------------------------------
    1 BVT-VERIFY-DEPLOYMENT-PROVISION                                                   PASS                 2.08
        FirstBoot : PASS
        Reboot : PASS
        Reboot : Call Trace Verification : PASS
```

Logs can be found at C:\GitHub\LISAv2-2\TestResults\2019-11-03-03-51-06-1411


03/11/2019 10:55:10 : [INFO ] Current Git Branch:  dbfix
03/11/2019 10:55:10 : [INFO ] Current Git Commit ID: cb096e2eebbc013130cd8802a53d6ba7f6b80d01
03/11/2019 10:55:10 : [INFO ] Creating 'C:\GitHub\LISAv2-2\HyperV-TH60-TestLogs.zip' from 'C:\GitHub\LISAv2-2\TestResults\2019-11-03-03-51-06-1411'
03/11/2019 10:55:10 : [INFO ] C:\GitHub\LISAv2-2\HyperV-TH60-TestLogs.zip created successfully.
03/11/2019 10:55:10 : [INFO ] Analyzing results..
03/11/2019 10:55:10 : [INFO ] LISAv2 exit code: 0

**Comment by juhlee-microsoft** [comment]
@iamshital The test result should show us what change will impact before and after. Your post does not mean to me.

**Comment by lizzha** [comment]
Maybe you need to update the database column before merging this PR, as it won't make trouble if the new column is nullable

**Comment by iamshital** [comment]
> @iamshital The test result should show us what change will impact before and after. Your post does not mean to me.

@juhlee-microsoft 

Result format before the PR, VMGeneration was not reported to DB.
----------------------------------------
03/11/2019 10:55:03 : [INFO ] SQLQuery:  INSERT INTO LISAv2Results (DateTimeUTC,TestPlatform,TestLocation,TestCategory,TestArea,TestName,TestResult,SubTestName,SubTestResult,ExecutionTag,GuestDistro,KernelVersion,LISVersion,HostVersion,VMSize,Networking,ARMImage,OsVHD,LogFile,BuildURL) VALUES ('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','','','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','1','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','FirstBoot','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','FirstBoot : Call Trace Verification','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','Reboot','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','Reboot : Call Trace Verification','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', '')
03/11/2019 10:55:03 : [INFO ] Uploading test results to database :  done!!

Result format after PR : VM Generation is reported to DB.
----------------------------------------
_Changes are marked in **Bold** style._
03/11/2019 10:55:03 : [INFO ] SQLQuery:  INSERT INTO LISAv2Results (DateTimeUTC,TestPlatform,TestLocation,TestCategory,TestArea,TestName,TestResult,SubTestName,SubTestResult,ExecutionTag,GuestDistro,KernelVersion,LISVersion,HostVersion,VMSize,**VMGeneration**,Networking,ARMImage,OsVHD,LogFile,BuildURL) VALUES ('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','','','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0',**'1'**,'Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','FirstBoot','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0',**'1'**,'Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','FirstBoot : Call Trace Verification','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0',**'1'**,'Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','Reboot','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0','1','Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', ''),('2019-3-11 10:55:0','HyperV','lis-f2325','BVT','BVT','BVT-VERIFY-DEPLOYMENT-PROVISION','PASS','Reboot : Call Trace Verification','PASS','','CentOS release 6.8 (Final)','2.6.32-642.el6.x86_64','3.1','14393-10.0-2-0.2636','Basic_A0',**'1'**,'Synthetic','','\\redmond\wsscfs\OSTC\LIS\VHD\Cloudbase\CentOS\CentOS_6.8_x64\centos_6.8x64.vhdx','https://XXXXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/lisav2logs/2019-3-11/BVT-VERIFY-DEPLOYMENT-PROVISION-636878733005871865.zip', '')
03/11/2019 10:55:03 : [INFO ] Uploading test results to database :  done!!

**Review by lizzha — APPROVED** [review]

**Comment by iamshital** [comment]
> Maybe you need to update the database column before merging this PR, as it won't make trouble if the new column is nullable

VMGenaration Column is added and execution is reverified.

**Pull request merged**
