### PR TITLE
Enable -RunInParallel

### PR DESCRIPTION
**Pull request by harz566**
- Enable RunInParallel with optional switch parameter `-RunInParallel` and another optional parameter `-TotalCountInParallel`, see the updated ReadMe document.
    * The switch test parameters `-RunInParallel` will start multiple processes to Run-LISAv2 in parallel on Azure platform. By default, the number of processes in parallel will be 'numberoflogicalprocessors' of the current Orchestrator machine (or vCPU number of the Orchestrator VM). Another optional parameter `-TotalCountInParallel` can be used to set the expected processes total count, if user does not prefer the default value. Note, other platforms except Azure may not support `-RunInParallel` successfully, because they may depends on various specific platform settings.

- Without using `-RunInParallel`, LISAv2 behaves exactly as before, no any breaking changes that is incompatible. 

- Fix a few other small bugs.

Note: JUnit or other test aspects may not formatted perfectly at the end of RunInParallel, that needs some additional efforts (not prioritized in this PR).
      
================Test Logs (Run-LISAv2 with -RunInParallel)=====================
11/02/2020 09:43:22 : [INFO ] Prepare test log structure and start testing now ...
11/02/2020 09:43:23 : [INFO ] YL38-1 is still running
11/02/2020 09:43:23 : [INFO ] YL38-2 is still running
11/02/2020 09:43:23 : [INFO ] There are 2 jobs are still running, will check again after 180 seconds...
11/02/2020 09:46:23 : [INFO ] YL38-1 is still running
11/02/2020 09:46:23 : [INFO ] YL38-2 is still running
11/02/2020 09:46:23 : [INFO ] There are 2 jobs are still running, will check again after 180 seconds...
11/02/2020 09:49:23 : [INFO ] YL38-1 finished
[YL38-1] |> 11/02/2020 09:43:23 : [INFO ] 
....
....
[YL38-2] |> 11/02/2020 09:48:41 : [INFO ] Analyzing test results ...
[YL38-2] |> 11/02/2020 09:48:41 : [INFO ] LISAv2 exit code: 0
11/02/2020 09:49:25 : [INFO ] 
[[================ All Parallel Test Finished ================]]
11/02/2020 09:49:25 : [INFO ] Test YL38 finished
11/02/2020 09:49:25 : [INFO ] 
[LISAv2 Test Results Summary]
Test Run On           : 11/02/2020 09:43:22
ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : Latest
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : Latest
Total Test Cases      : 2 (0 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:6

[LISAv2 Test Results Summary]
Test Run On           : 11/02/2020 09:44:03
ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : Latest
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : Latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:4

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 VERIFY-DEPLOYMENT-PROVISION                                                       PASS                 2.07 
      ARMImageName: Canonical UbuntuServer 16.04-LTS Latest, TestLocation: westus2, Kernel Version: 4.15.0-1098-azure
      FirstBoot : PASS
      FirstBoot : Call Trace Verification : PASS
      Reboot : PASS
      Reboot : Call Trace Verification : PASS
      

Logs can be found at C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\TestResults\2020-11-02-09-43-23-YL38-1

11/02/2020 09:48:34 : [DEBUG] Creating 'C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\Azure-YL38-1-TestLogs.zip' from 'C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\TestResults\2020-11-02-09-43-23-YL38-1'
11/02/2020 09:48:34 : [DEBUG] C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\Azure-YL38-1-TestLogs.zip created successfully.
11/02/2020 09:48:34 : [INFO ] Analyzing test results ...
11/02/2020 09:48:34 : [INFO ] LISAv2 exit code: 0
[LISAv2 Test Results Summary]
Test Run On           : 11/02/2020 09:44:03
ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : Latest
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : Latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:4

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 VERIFY-DEPLOYMENT-PROVISION                                                       PASS                 2.17 
      ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, TestLocation: westus2, Kernel Version: 5.4.0-1031-azure
      FirstBoot : PASS
      FirstBoot : Call Trace Verification : PASS
      Reboot : PASS
      Reboot : Call Trace Verification : PASS
      

Logs can be found at C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\TestResults\2020-11-02-09-43-23-YL38-2

11/02/2020 09:48:41 : [DEBUG] Creating 'C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\Azure-YL38-2-TestLogs.zip' from 'C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\TestResults\2020-11-02-09-43-23-YL38-2'
11/02/2020 09:48:41 : [DEBUG] C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\Azure-YL38-2-TestLogs.zip created successfully.
11/02/2020 09:48:41 : [INFO ] Analyzing test results ...
11/02/2020 09:48:41 : [INFO ] LISAv2 exit code: 0

Logs can be found at C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\TestResults\2020-11-02-09-43-18-YL38

11/02/2020 09:49:25 : [DEBUG] Creating 'C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\Azure-YL38-TestLogs.zip' from 'C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\TestResults\2020-11-02-09-43-18-YL38'
11/02/2020 09:49:25 : [DEBUG] C:\jenkins-slave-executor-1\workspace\Azure\job-azure-cloudtest-manual@2\Azure-YL38-TestLogs.zip created successfully.
11/02/2020 09:49:25 : [INFO ] Analyzing test results ...
11/02/2020 09:49:25 : [INFO ] Forcefully exiting with exit code 0 as ExitWithZero flag was set to True
11/02/2020 09:49:25 : [INFO ] LISAv2 exit code: 0

==========>>>>>>>>>>>>>>>>>Test Logs (Normal without RunInParallel) <<<<<<<<<<<<<<<<============
[LISAv2 Test Results Summary]
Test Run On           : 11/02/2020 09:42:05
ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : Latest
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : Latest
Total Test Cases      : 2 (2 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:8

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 VERIFY-DEPLOYMENT-PROVISION                                                       PASS                 1.95 
      ARMImageName: Canonical UbuntuServer 16.04-LTS Latest, TestLocation: westus2, Kernel Version: 4.15.0-1098-azure
      FirstBoot : PASS
      FirstBoot : Call Trace Verification : PASS
      Reboot : PASS
      Reboot : Call Trace Verification : PASS
      
    2 CORE                 VERIFY-DEPLOYMENT-PROVISION                                                       PASS                 2.14 
      ARMImageName: Canonical UbuntuServer 18.04-LTS Latest, TestLocation: westus2, Kernel Version: 5.4.0-1031-azure
      FirstBoot : PASS
      FirstBoot : Call Trace Verification : PASS
      Reboot : PASS
      Reboot : Call Trace Verification : PASS

### CODE REVIEW

**Comment by squirrelsc** [comment]
1. Are the format rules used by all the team? I'm not sure if someone may format it back.
2. @LiliDeng is it the change in onebox testing?

**Comment by harz566** [comment]
> 1. Are the format rules used by all the team? I'm not sure if someone may format it back.
> 2. @LiliDeng is it the change in onebox testing?

If don't RunInParallel (Run as usual), no format changed in Test Summary, and JUnit or other test report aspects

**Comment by squirrelsc** [comment]
> > 1. Are the format rules used by all the team? I'm not sure if someone may format it back.
> > 2. @LiliDeng is it the change in onebox testing?
> 
> If don't RunInParallel (Run as usual), no format changed in Test Summary, and JUnit or other test report aspects

I see there are some format changes like indent, whitespaces. I'm not sure if someone use different format rules, so that they may be format back.

**Comment by harz566** [comment]
> > > 1. Are the format rules used by all the team? I'm not sure if someone may format it back.
> > > 2. @LiliDeng is it the change in onebox testing?
> > 
> > 
> > If don't RunInParallel (Run as usual), no format changed in Test Summary, and JUnit or other test report aspects
> 
> I see there are some format changes like indent, whitespaces. I'm not sure if someone use different format rules, so that they may be format back.

Oh, those are auto formatted changes with VSCode Powershell extension. (Auto formatted when saving).  General reason is previous code is not following the recommended format rules aligned to the PowerShell extension.   So, no worries.

**Review by squirrelsc — DISMISSED** [review]
leave regression risk checking to @LiliDeng. It looks good to me.

**Review by squirrelsc — DISMISSED** [review]

**Review by LiliDeng — APPROVED** [review]

**Review by squirrelsc — APPROVED** [review]

**Pull request merged**
