### PR TITLE
Add initial and final kernel version to Test Summary

### LINKED ISSUE #450: kernel versions display
This issue comes back from the old discussion, and I still need it inside of Test Summary. Add the initial kernel version and final kernel version lines in Test Summary page?

### PR DESCRIPTION
**Pull request by Tong-Xu**
Fix https://github.com/LIS/LISAv2/issues/450
Test results:
```
[LISAv2 Test Results Summary]
Test Run On           : 07/18/2019 06:54:56
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-DAILY-LTS : latest
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1025-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:16

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1                      CAPTURE-VHD-BEFORE-TEST                                                           PASS                 7.57 

[LISAv2 Test Results Summary]
Test Run On           : 07/18/2019 06:43:58
ARM Image Under Test  : OpenLogic : CentOS : 7.6 : 7.6.20190708
Initial Kernel Version: 3.10.0-957.21.3.el7.x86_64
Final Kernel Version  : 3.10.0-957.21.3.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:16

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 LIS_DEPLOY           LIS-DEPLOY-SCENARIO-1                                                             PASS                12.65 
	Install-LIS-Scenario-1 : PASS 

[LISAv2 Test Results Summary]
Test Run On           : 07/18/2019 06:56:27
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1024-azure
Total Test Cases      : 3 (3 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:12

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 VERIFY-LINUX-CONFIGURATION                                                        PASS                 2.98 
    2 CORE                 LIS-MODULES-CHECK                                                                 PASS                 2.91 
    3 CORE                 VERIFY-LIS-MODULES-VERSION                                                        PASS                 2.65
```

### CODE REVIEW

**Comment by LiliDeng** [comment]
Test results - 
```
[LISAv2 Test Results Summary]
Test Run On           : 07/18/2019 07:49:08
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1025-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:14

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1                      CAPTURE-VHD-BEFORE-TEST                                                           PASS                 6.29 

[LISAv2 Test Results Summary]
Test Run On           : 07/18/2019 07:31:18
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1024-azure
Total Test Cases      : 2 (2 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:7

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 WALA                 WALA-VERIFY-HOSTNAME                                                              PASS                 0.85 
    2 WALA                 WALA-VERSION-CHECK                                                                PASS                 0.81 
```

**Comment by chvalean** [comment]
@Tong-Xu  please try to break the run of lisav2 so that it won't be able to get the final kernel version.
Would like to see what the output would be then, as it can happen that some exception might occur and the VM will not be reachable again, so the run will fail.

**Comment by LiliDeng** [comment]
@chvalean When test break, there will be no test summary? In normal situation, the VM can be accessed till the end, if not, the final kernel version will be empty, then we will not print it out, does it make sense?

**Review by chvalean — APPROVED** [review]

**Comment by chvalean** [comment]
> @chvalean When test break, there will be no test summary? In normal situation, the VM can be accessed till the end, if not, the final kernel version will be empty, then we will not print it out, does it make sense?

That's what I was curious - if it cannot get the final kernel, what would be the output? If you say it's blank, then fine.

**Review by juhlee-microsoft — APPROVED** [review]

**Pull request merged**
