### PR TITLE
More trivial fixes, for now

### PR DESCRIPTION
**Pull request by glima**

### CODE REVIEW

**Comment by squirrelsc** [comment]
1. The poetry.lock is auto generated, shouldn't be updated manually.
2. The files in typings are used to support typing prompt for those packages. If they are removed, no typing prompt for those packages.

**Review by squirrelsc — CHANGES_REQUESTED** [review]
1. The poetry.lock is auto generated, shouldn't be updated manually. Do you miss to push the pyproject.toml?
2. The files in typings are used to support typing prompt for those packages. If they are removed, no typing prompt for those packages.

**Comment by glima** [comment]
1. Of course it's auto-generated, but after issuing important Poetry commands, that will affect version for everybody. That file should be tracked, according to Poetry themselves: https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control. About the toml file, it was already there! "assertpy = "^1.1""
2. Yeah, I know, but the dep was already there, see the .toml :)

**Comment by glima** [comment]
BTW, after every git pull/fetch in which people see poetry changes, people are encouraged to issue poetry install (or make setup) again

**Comment by squirrelsc** [comment]
1. If it's not manual edited, it's ok to put it in. I couldn't find recommendation in the official site, to manual edit this file. It means needs to be checked after run `poetry update` every time. 
2. For typings folder, it supports type prompt tools like mypy. They are stub files for typing only, not implementation. The assertpy package itself doesn't support typing, so it needs to add them manually.

**Comment by glima** [comment]
1. Yes, after update :)
2. See below:

```
 glima  ~  .cache  …  python3.8  site-packages  assertpy  $  ls
assertpy.py  collection.py  date.py  dynamic.py    extracting.py  helpers.py   numeric.py   snapshot.py
base.py      contains.py    dict.py  exception.py  file.py        __init__.py  __pycache__  string.py
 glima  ~  .cache  …  python3.8  site-packages  assertpy  $  
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
commit 56fb63f560d7ad1f4d36bc9116bd3766964b3764                                                                                                               
Refs: [main]                                                                                                                                                  
Author:     Gustavo Lima Chaves <gustavo.chaves@microsoft.com>                                                                                                
AuthorDate: Thu Mar 18 15:26:01 2021 -0700                                                                                                                    
Commit:     Gustavo Lima Chaves <gustavo.chaves@microsoft.com>                                                                                                
CommitDate: Thu Mar 18 15:26:01 2021 -0700                                                                                                                    

    Remove hardcoded dependencies which were already in Poetry
---                                                                                                                                                           
 typings/assertpy/__init__.pyi   |  9 -----                                                                                                                   
 typings/assertpy/assertpy.pyi   | 69 ---------------------------------------                                                                                 
 typings/assertpy/base.pyi       | 20 ------------                                                                                                            
 typings/assertpy/collection.pyi | 13 --------                                                                                                                
 typings/assertpy/contains.pyi   | 19 -----------                                                                                                             
 typings/assertpy/date.pyi       | 12 -------                                                                                                                 
 typings/assertpy/dict.pyi       | 13 --------                                                                                                                
 typings/assertpy/dynamic.pyi    | 10 ------                                                                                                                  
 typings/assertpy/exception.pyi  | 13 --------                                                                                                                
 typings/assertpy/extracting.pyi | 11 -------                                                                                                                 
 typings/assertpy/file.pyi       | 16 ---------                                                                                                               
 typings/assertpy/helpers.pyi    |  6 ----                                                                                                                    
 typings/assertpy/numeric.pyi    | 23 -------------                                                                                                           
 typings/assertpy/snapshot.pyi   | 10 ------                                                                                                                  
 typings/assertpy/string.pyi     | 22 -------------                                                                                                           
 typings/pluggy/__init__.pyi     |  7 ----                                                                                                                    
 typings/pluggy/hooks.pyi        | 45 -------------------------                                                                                               
 typings/pluggy/manager.pyi      | 47 --------------------------                                                                                              

```
So what I'm removing is exactly what is brought in by Poetry and the package. Context: ls of package contents, inside Poetry env., at the top, and my commit at the bottom.

**Comment by squirrelsc** [comment]
For assertpy, I double checked current version (1.1), it doesn't support typing yet.

The difference is below. 

from implementation (installed files, and in assertpy codebase)
```python
def assert_that(val, description=""):
```

from typing stub (in our code base)
```python
def assert_that(val: Any, description: str = ...) -> AssertionBuilder: ...
```

So that, when use a tool support type prompt, after `assert_that(something)`, then type a dot `.`  It will list all assert candidates' methods in `AssertionBuilder`.

**Comment by squirrelsc** [comment]
For assertpy, I double checked current version (1.1), it doesn't support typing yet.

The difference is below. 

from implementation (installed files, and in assertpy codebase)
```python
def assert_that(val, description=""):
```

from typing stub (in our code base)
```python
def assert_that(val: Any, description: str = ...) -> AssertionBuilder: ...
```

So that, when use a tool support type prompt, after `assert_that(something).` . It will list all assert candidates' methods in `AssertionBuilder`.

**Comment by glima** [comment]
Oh, I guess I don't stress out about code completion as much. OK, I'll drop that commit, for now.

**Review by squirrelsc — APPROVED** [review]
Thank you!
We will provide best experience on test development. So, the typing of key packages are in our codebase.

**Pull request merged**
