### PR TITLE
BVT consolidation - part 2

### PR DESCRIPTION
**Pull request by chvalean**
Further moving tests out of BVT.xml.

Changes summary:
- removed BVT-VERIFY-SHUTDOWN and BVT-VERIFY-RESTART as obsolete.
- remove duplicate test check VERIFY-LIS-MODULES and replacing with the py script.
- move timesync and related TCs to functional tests.

### CODE REVIEW

**Comment by juhlee-microsoft** [comment]
As soon as all changed test passed, let me approve.

**Comment by chvalean** [comment]
Test results

```
[LISAv2 Test Results Summary]
Test Run On           : 04/15/2019 23:28:34
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : latest
Total Test Cases      : 8 (8 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:28

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 TIME-CLOCKEVENT-SMP                                                               PASS                 1.17
    2 WALA                 WALA-VERIFY-WAAGENT-LOG                                                           PASS                 1.33
    3 WALA                 WALA-VERIFY-VERBOSE-ENABLED-LOGS                                                  PASS                 2.65
    4 CORE                 VERIFY-DEPLOYMENT-PROVISION                                                       PASS                 3.16
        FirstBoot : PASS
        FirstBoot : Call Trace Verification : PASS
        Reboot : PASS
        Reboot : Call Trace Verification : PASS
    5 CORE                 LIS-MODULES-CHECK                                                                 PASS                 1.68
    6 CORE                 VERIFY-VHD-PREREQUISITES                                                          PASS                 2.35
    7 CORE                 TIMESYNC-NTP                                                                      PASS                 1.93
    8 CORE                 VERIFY-DEPLOYMENT-PROVISION-SRIOV                                                 PASS                 3.02
        FirstBoot : PASS
        FirstBoot : Call Trace Verification : PASS
        Reboot : PASS
        Reboot : Call Trace Verification : PASS

```

**Comment by chvalean** [comment]
> As soon as all changed test passed, let me approve.

Test results added, still going through the code so please do not merge until PR tags are updated.

**Comment by chvalean** [comment]
@juhlee-microsoft  all checks have passed, feel free to do final check and merge it please.

**Review by juhlee-microsoft — APPROVED** [review]

**Pull request merged**
