### PR TITLE
Add pending test count in test summary.

### PR DESCRIPTION
**Pull request by harz566**
1. Update TestSummaryForCase  add Pending number.

### CODE REVIEW

**Comment by juhlee-microsoft** [comment]
@harz566 It looks good, but do you have any change test log?

**Review by juhlee-microsoft — APPROVED** [review]
Hope to see the test result. I wonder that pending line printing.

**Comment by harz566** [comment]
02/08/2020 06:05:04 : [INFO ] End of testing: WALA-VERIFY-HOSTNAME , result: PASS
02/08/2020 06:05:04 : [INFO ] PASS    - 1
02/08/2020 06:05:04 : [INFO ] SKIPPED - 0
02/08/2020 06:05:04 : [INFO ] FAIL    - 0
02/08/2020 06:05:04 : [INFO ] ABORTED - 0
02/08/2020 06:05:04 : [INFO ] PENDING - 1 

02/08/2020 06:05:04 : [INFO ] (2/2) testing started: WALA-VERIFY-MNT-RESOURCE-README

**Comment by juhlee-microsoft** [comment]
Let me check some conditions and come back here. Please keep open this a while.

**Pull request merged**
