### PR TITLE
Extend sleep time if hit 404 issue when restart VM on azure.

### PR DESCRIPTION
**Pull request by LiliDeng**
We hit this issue when azure backend services deal with multiple request during running pipeline.
#33 is a fix, but this issue still happen, we overserve that this issues will last during a few minutes.
So try to extend the wait time, let's see how it is going.

```
[LISAv2 Test Results Summary]
Test Run On           : 03/29/2019 00:27:55
ARM Image Under Test  : OpenLogic : CentOS : 7.5 : Latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:36

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 STRESS               STRESSTEST-VERIFY-RESTART-MAX-SRIOV-NICS                                          PASS                26.49 
```

### CODE REVIEW

**Comment by lizzha** [comment]
instead of merging it then check whether it works, can you test it by changing the LISAv2 branch in pipeline?

**Comment by juhlee-microsoft** [comment]
still PR testing?

**Comment by LiliDeng** [comment]
Will finish it today, thanks for your review. @juhlee-microsoft

**Review by juhlee-microsoft — APPROVED** [review]

**Comment by LiliDeng** [comment]
Previous fix not working, issue happen again.
Now use another way try to fix, during testing now.

**Comment by LiliDeng** [comment]
To reduce noise, close this one, will send out PR once find valid solution.

**Pull request closed without merging**
