### PR TITLE
Support GPU on SLES

### LINKED ISSUE #349: GPU: skip run on SLES
SLES is not spported for NVIDIA GPU drivers on N-series VM

Ref: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup

### PR DESCRIPTION
**Pull request by v-sijliu**
Fixes #349 

```
[LISAv2 Test Results Summary]
Test Run On           : 07/01/2019 07:37:02
ARM Image Under Test  : SUSE : SLES : 15 : Latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:12

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-CUDA-DRIVER-VALIDATION                                                     PASS                 7.59 
	Using nVidia driver : CUDA 
	lsvmbus: Expected "PCI Express pass-through" count: 1, count inside the VM: 1 : PASS 
	lspci: Expected "3D controller: NVIDIA Corporation" count: 1, found inside the VM: 1 : PASS 
	lshw: Expected Display adapters: 1, total adapters found in VM: 1 : PASS 
	nvidia-smi: Expected GPU count: 1, found inside the VM: 0 : FAIL 
```

### CODE REVIEW

**Comment by chvalean** [comment]
@LiliDeng  @v-sijliu have you confirmed that SLES is indeed supported in Azure? And that the Azure documentation has to be update to also include SLES?

**Comment by LiliDeng** [comment]
@chvalean Ava made a mistake here, need further investigation.

nvidia-smi: Expected GPU count: 1, found inside the VM: 0 : FAIL

**Comment by LiliDeng** [comment]
Close this one, will submit new one once get further progress.

**Comment by juhlee-microsoft** [comment]
> @chvalean Ava made a mistake here, need further investigation.
> 
> nvidia-smi: Expected GPU count: 1, found inside the VM: 0 : FAIL

This is what I see today and request to skip SLES 15. @v-sijliu @LiliDeng ok with it?

**Pull request closed without merging**
