### PR TITLE
xml: fix global config indentation

### PR DESCRIPTION
**Pull request by ader1990**
LISAv2 code changes this xml and reformats it with the current patch indentation.
This leads to a huge diff which makes other changes you have made to the code harder to see.

Partially addresses: https://github.com/LIS/LISAv2/issues/148

### CODE REVIEW

**Comment by iamshital** [comment]
@ader1990  Why are we changing from 4 spaces to 2 space indentation?

**Comment by ader1990** [comment]
> @ader1990 Why are we changing from 4 spaces to 2 space indentation?

because LISAv2 code changes this xml and reformats it with the current patch indentation.
This leads to a huge diff which makes other changes you have made to the code harder to see.

**Comment by iamshital** [comment]
> > @ader1990 Why are we changing from 4 spaces to 2 space indentation?
> 
> because LISAv2 code changes this xml and reformats it with the current patch indentation.
> This leads to a huge diff which makes other changes you have made to the code harder to see.

I would go for self-analysis of the changed XML file, rather than putting the inconsistency in LISAv2 code for our own sake.

**Comment by ader1990** [comment]
> > > @ader1990 Why are we changing from 4 spaces to 2 space indentation?
> > 
> > 
> > because LISAv2 code changes this xml and reformats it with the current patch indentation.
> > This leads to a huge diff which makes other changes you have made to the code harder to see.
> 
> I would go for self-analysis of the changed XML file, rather than putting the inconsistency in LISAv2 code for our own sake.

as a matter of fact, the other xmls have space indentation. this one is the only one inconsistency in the xmls, and my PR fixes that inconsistency.

**Comment by iamshital** [comment]
> > > > @ader1990 Why are we changing from 4 spaces to 2 space indentation?
> > > 
> > > 
> > > because LISAv2 code changes this xml and reformats it with the current patch indentation.
> > > This leads to a huge diff which makes other changes you have made to the code harder to see.
> > 
> > 
> > I would go for self-analysis of the changed XML file, rather than putting the inconsistency in LISAv2 code for our own sake.
> 
> as a matter of fact, the other xmls have space indentation. this one is the only one inconsistency in the xmls, and my PR fixes that inconsistency.

I see 4 spaces in other XMLs while this one is using 2 space?

**Comment by ader1990** [comment]
@iamshital this is an old issue that I think comes as a legacy mode of doing things in lisav2:
https://github.com/LIS/LISAv2/commit/0d18d364

Right now, what would be the purpose of changing the global config xml and saving it?
Isn t it enough to just change the config object during lisav2 run and not save the new xml?

I refer to just removing this line here: https://github.com/LIS/LISAv2/blob/master/TestControllers/AzureController.psm1#L137

**Comment by iamshital** [comment]
> Isn t it enough to just change the config object during lisav2 run and not save the new xml

Agree. It's good suggestion.

**Comment by ader1990** [comment]
> > Isn t it enough to just change the config object during lisav2 run and not save the new xml
> 
> Agree. It's good suggestion.

will close this PR and open another PR with the removal of the global configuration save.

**Pull request closed without merging**
