### PR TITLE
Add support for custom kernel on sles

### LINKED ISSUE #52: SLES: add suport for -CustomKernel "localfile:"
Lisav2 does not support installing custom kernel on SLES 15/SLES 12.

### LINKED ISSUE #53: HyperV: Add support for custom kernel install for generation 2 VMs
LISAv2 fails to modify the proper grub.cfg on efi systems, as the path is no longer /boot/grub/grub.cfg.

Depending on the distro version, that path can be:

1. RHEL - /boot/efi/rhel/grub/grub.cfg
1. SLES - /boot/efi/sles/grub/grub.cfg

Ubuntu path must be checked too.

### PR DESCRIPTION
**Pull request by stefanlupsa**
* proper handling for grub config on efi systems
* add `remove_package` to `utils.sh` to mirror `install_package` function

Fixes #52 
Partially Fixes #53 for rhel and suse based distros

### CODE REVIEW

**Review by juhlee-microsoft — COMMENTED** [review]
Please post the result with distro RHEL and SUSE.

**Review by lizzha — APPROVED** [review]

**Comment by lizzha** [comment]
Approved for code change, will merge after test results posted

**Comment by stefanlupsa** [comment]
**CentOS 7.6**: 
```
03-25-2019 16:07:41 : [INFO ] Old kernel: 3.10.0-957.el7.x86_64
03-25-2019 16:07:41 : [INFO ] New kernel: 5.1.0-rc1-next-20190320-835727301ed3
```

```
[LISAv2 Test Results Summary]
Test Run On           : 03/25/2019 16:04:17
VHD Under Test        : C:\HDDs\CentOS-7.6.vhdx
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:4

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LSVMBUS                                                                           PASS                  0.6 


Logs can be found at C:\Work\LISAv2\TestResults\2019-25-03-18-04-16-6604
```
---
**SLES 15**:
```
03-25-2019 15:18:14 : [INFO ] Old kernel: 4.12.14-5.19-azure
03-25-2019 15:18:14 : [INFO ] New kernel: 5.1.0-rc1-next-20190320-835727301ed3
```
```
[LISAv2 Test Results Summary]
Test Run On           : 03/25/2019 15:15:08
VHD Under Test        : C:\HDDs\sles15-azure-dyn.vhdx
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:12

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LSVMBUS                                                                           PASS                 7.54 


Logs can be found at C:\Work\LISAv2\TestResults\2019-25-03-17-15-07-8796
```

**Comment by stefanlupsa** [comment]
**CentOS 7.6**: 
```
03-25-2019 16:07:41 : [INFO ] Old kernel: 3.10.0-957.el7.x86_64
03-25-2019 16:07:41 : [INFO ] New kernel: 5.1.0-rc1-next-20190320-835727301ed3
```

```
[LISAv2 Test Results Summary]
Test Run On           : 03/25/2019 16:04:17
VHD Under Test        : CentOS-7.6.vhdx
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:4

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LSVMBUS                                                                           PASS                  0.6 
```
---
**SLES 15**:
```
03-25-2019 15:18:14 : [INFO ] Old kernel: 4.12.14-5.19-azure
03-25-2019 15:18:14 : [INFO ] New kernel: 5.1.0-rc1-next-20190320-835727301ed3
```
```
[LISAv2 Test Results Summary]
Test Run On           : 03/25/2019 15:15:08
VHD Under Test        : sles15-azure-dyn.vhdx
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:12

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LSVMBUS                                                                           PASS                 7.54 
```

**Review by juhlee-microsoft — APPROVED** [review]

**Pull request merged**
