### PR TITLE
DPDK: Change installation steps as make is deprecated

### PR DESCRIPTION
**Pull request by abhimarathe**
Removed make steps and added meson steps

 PERF-DPDK-SINGLE-CORE-PPS-DS4  below shows failed : the reason of failure is not installation or running of testpmd as you can see the result. The reason is due to a known issue with mellanox mlx4/CX-3 NIC.
```
[LISAv2 Test Results Summary]
Test Run On           : 08/10/2020 22:05:54
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:26

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-BUILD-AND-TESTPMD-TEST                                                PASS                22.38 
      ARMImageName: Canonical UbuntuServer 18.04-LTS latest, Networking: SRIOV, TestLocation: eastus2, Kernel Version: 5.3.0-1034-azure


Logs can be found at C:\LISAv2\TE91\TestResults\2020-08-10-15-04-48-5695


[LISAv2 Test Results Summary]
Test Run On           : 08/10/2020 18:47:48
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Test Cases      : 1 (0 Passed, 1 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:19

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 PERF-DPDK-SINGLE-CORE-PPS-DS4                                                     FAIL                15.46
      ARMImageName: Canonical UbuntuServer 18.04-LTS latest, Networking: SRIOV, OverrideVMSize: Standard_DS4_v2, TestLocation: eastus2, Initial Kernel Version: 5.3.0-1034-azure
      dpdk_version test_mode core max_rx_pps tx_pps_avg rx_pps_avg fwdtx_pps_avg tx_bytes   rx_bytes  fwd_bytes
------------ --------- ---- ---------- ---------- ---------- ------------- --------   --------  ---------
20.08.0-rc3  rxonly    1    296488     406872     250160     0             1574703015 951496090 0
20.08.0-rc3  io        1    1          797792     0          0             3165029270 738       648



Logs can be found at C:\LISAv2\YO58\TestResults\2020-08-10-11-46-44-8001
```

### CODE REVIEW

**Comment by harz566** [comment]
Do we have a passed test log of 8/10? Just see the Failed one on 08/10 and Passed one on 08/06

**Comment by abhimarathe** [comment]
```
[LISAv2 Test Results Summary]
Test Run On           : 08/10/2020 22:05:54
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:26

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-BUILD-AND-TESTPMD-TEST                                                PASS                22.38 
      ARMImageName: Canonical UbuntuServer 18.04-LTS latest, Networking: SRIOV, TestLocation: eastus2, Kernel Version: 5.3.0-1034-azure


Logs can be found at C:\LISAv2\TE91\TestResults\2020-08-10-15-04-48-5695

```

**Review by harz566 — DISMISSED** [review]

**Review by lubaihua33 — DISMISSED** [review]

**Comment by abhimarathe** [comment]
```
[LISAv2 Test Results Summary]
Test Run On           : 08/13/2020 19:08:38
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:20

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-PRIMARY-SECONDARY-PROCESSES                                           PASS                17.26
      ARMImageName: Canonical UbuntuServer 18.04-LTS latest, Networking: SRIOV, OverrideVMSize: Standard_D16s_v3, TestLocation: eastus2, Initial Kernel Version: 5.3.0-1034-azure


Logs can be found at C:\LISAv2\XZ79\TestResults\2020-08-13-12-07-55-0261
```

**Comment by abhimarathe** [comment]
```
[LISAv2 Test Results Summary]
Test Run On           : 08/13/2020 23:20:07
ARM Image Under Test  : OpenLogic : CentOS : 7.6 : latest
Total Time (dd:hh:mm) : 0:0:10

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-COMPLIANCE                                                            PASS                 7.48
      ARMImageName: OpenLogic CentOS 7.6 latest, Networking: SRIOV, TestLocation: eastus2, Initial Kernel Version: 3.10.0-957.27.2.el7.x86_64


Logs can be found at C:\LISAv2\DY76\TestResults\2020-08-13-16-19-22-4872
```

**Review by harz566 — APPROVED** [review]

**Review by lubaihua33 — APPROVED** [review]

**Review by LiliDeng — APPROVED** [review]

**Pull request merged**
