### PR TITLE
Enhance lsvmbus.

### PR DESCRIPTION
**Pull request by LiliDeng**
- Remove special handle for Standard_Lxs_v2
- Use VM with 2 nics attached and size Standard_D32s_v3 which may contain more than 1 numa node
- Check channel count for each network adapter and SCSI controller
- Check channels spread into numa node properly, not only distribute to 1 numa node unless if only have one.

```
[LISAv2 Test Results Summary]
Test Run On           : 04/26/2021 04:09:55
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:2

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LSVMBUS                                                                           PASS                  0.7 
      ARMImageName: Canonical UbuntuServer 18.04-LTS 18.04.202104150, OverrideVMSize: Standard_D32s_v3, TestLocation: westus2, Kernel Version: 5.4.0-1046-azure

[LISAv2 Test Results Summary]
Test Run On           : 04/26/2021 04:09:49
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Override VM size Under Test  : Standard_DS4_v2
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:2

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LSVMBUS                                                                           PASS                  0.7 
      ARMImageName: Canonical UbuntuServer 18.04-LTS 18.04.202104150, OverrideVMSize: Standard_DS4_v2, TestLocation: westus2, Kernel Version: 5.4.0-1046-azure
```

### CODE REVIEW

**Comment by squirrelsc** [comment]
Is there anything needed in v3?

**Comment by LiliDeng** [comment]
> Is there anything needed in v3?

logic of 'channels spread into different numa node' doesn't exist in lisav3 yet. Other part is to enhance lisav2 lsvmbus test case.

**Comment by squirrelsc** [comment]
Is it not migrated test case? if it's not, we may need add a task.

> > Is there anything needed in v3?
> 
> logic of 'channels spread into different numa node' doesn't exist in lisav3 yet. Other part is to enhance lisav2 lsvmbus test case.

**Comment by LiliDeng** [comment]
> Is it not migrated test case? if it's not, we may need add a task.

No, this PR is an old task to enhance/correct lsvmbus logic, I will add a task for lisav3.

**Comment by squirrelsc** [comment]
@LiliDeng is it fully migrated? Can we close this PR?

**Pull request closed without merging**
