### PR TITLE
Pylint: Enable modified-iterating-list

### PR DESCRIPTION
**Pull request by avylove**
Modifying an iterator while iterating over it can have unexpected behavior.
Enables modified-iterating-list check and fixes code.

### CODE REVIEW

**Comment by avylove** [comment]
@squirrelsc , @LiliDeng Any issues with this?

**Comment by squirrelsc** [comment]
> @squirrelsc , @LiliDeng Any issues with this?


It touches the core part, we don't have a chance to verify it.

**Comment by avylove** [comment]
Rebased. This is now 3.5 months old.

**Comment by squirrelsc** [comment]
Please either test with impacted scenarios or suppress this code to enable the rule. This place is safe, because the iterator is broken out after modified.

**Pull request closed without merging**
