### PR TITLE
change cpu cases to use 16 core, and fix channel count reset logic

### PR DESCRIPTION
**Pull request by LiliDeng**
- if no core requirement setting, the case will be skipped since no idle cpu used for testing.
- after offline the idel cpu, the max channel count changed into cpu_count - idle_cpus count, only can set current channel between 1 and current max channel, otherwise, ethtool command will fail

### CODE REVIEW

**Comment by squirrelsc** [comment]
What's the reason it needs 32 cores? Should 2 cores be enough to have an idle cpu? The comments should be in test case metadata to let others know where the core requirement is from.

**Comment by LiliDeng** [comment]
> 

I tried 16 core, the case still be skipped for no idle core to be tested

**Comment by squirrelsc** [comment]
> > 
> 
> I tried 16 core, the case still be skipped for no idle core to be tested

Does it need an actual idle cpu? If so, any count of cores maybe failed. How about wait a moment for an idle cpu core?

**Comment by LiliDeng** [comment]
> > > 
> > 
> > 
> > I tried 16 core, the case still be skipped for no idle core to be tested
> 
> Does it need an actual idle cpu? If so, any count of cores maybe failed. How about wait a moment for an idle cpu core?

the case is to verify taking idle cpu offline/online. we can't take working cpu offline.
newer kernel supports to update workload's target cpu into 0, then take remain ones (idle cpu) offline/online. but most of current distros don't support it, we have to rely on current idle cpus in system.

I will check whether wait for a while help or not.

**Comment by LiliDeng** [comment]
> > > 
> > 
> > 
> > I tried 16 core, the case still be skipped for no idle core to be tested
> 
> Does it need an actual idle cpu? If so, any count of cores maybe failed. How about wait a moment for an idle cpu core?

no lucky if add wait, I try 2 cores, 16 cores, after 1 hour, still no idle cpu, I think the kernel will try to distribute workload into different cpus. that's why we see different target cpu distributed when run lsvmbus -vvv

**Review by squirrelsc — APPROVED** [review]

**Pull request merged**
