### PR TITLE
Debian 13 Arm16 testing

### PR DESCRIPTION
**Pull request by rabdulfaizy**
…gives "trixie/sid" which throws Assertion Error. Hardcoding the version value to "13.0" to run the tests

### CODE REVIEW

**Comment by squirrelsc** [comment]
@rabdulfaizy What's this PR for? It just hard code a version. Please close the PR, until it's ready for reviewing or preview.

**Comment by squirrelsc** [comment]
@rabdulfaizy I gave you write permission of this repo. please create test branches, not PRs.

**Comment by rabdulfaizy** [comment]
[like]  Raheel Abdul Faizy reacted to your message:
________________________________

**Comment by rabdulfaizy** [comment]
Closing the PR.

**Pull request closed without merging**
