### PR TITLE
Fix spur's connection timeout setting 

### PR DESCRIPTION
**Pull request by glima**
...against values from the command line.

### CODE REVIEW

**Comment by glima** [comment]
OK, let this lazy dev figure out the tests first

**Comment by squirrelsc** [comment]
I had a fix, and pushed in below branch. If it blocks something, can you cherry pick it?

https://github.com/microsoft/lisa/tree/chisong/transformer

**Comment by glima** [comment]
Let me see. As a note, why would an unnamed variable be ever allowed?

**Comment by glima** [comment]
Whatever works, not in a hurry (this fix worked at runtime just fine, as there are no unnamed ones). My question remains :)

**Comment by squirrelsc** [comment]
> Let me see. As a note, why would an unnamed variable be ever allowed?

What's the context of the question? Where is it from?

**Comment by glima** [comment]
ERROR: test_in_runbook_format_file (tests.test_variable.VariableTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/glima/code/lisa/lisa-v3/lisa/tests/test_variable.py", line 82, in test_in_runbook_format_file
    data = self._test_runbook_file_entry(
  File "/home/glima/code/lisa/lisa-v3/lisa/tests/test_variable.py", line 267, in _test_runbook_file_entry
    variables.update(variable._load_from_runbook(data, current_variables))
  File "/home/glima/code/lisa/lisa-v3/lisa/variable.py", line 177, in _load_from_runbook
    current_variables[entry.name].is_case_visible = loaded_variables[
KeyError: ''


The fail on the tests.

**Comment by squirrelsc** [comment]
> ## ERROR: test_in_runbook_format_file (tests.test_variable.VariableTestCase)
> Traceback (most recent call last):
> File "/home/glima/code/lisa/lisa-v3/lisa/tests/test_variable.py", line 82, in test_in_runbook_format_file
> data = self._test_runbook_file_entry(
> File "/home/glima/code/lisa/lisa-v3/lisa/tests/test_variable.py", line 267, in _test_runbook_file_entry
> variables.update(variable._load_from_runbook(data, current_variables))
> File "/home/glima/code/lisa/lisa-v3/lisa/variable.py", line 177, in _load_from_runbook
> current_variables[entry.name].is_case_visible = loaded_variables[
> KeyError: ''
> 
> The fail on the tests.

It's a load from file entry, not a name/value entry. So it has no name.

**Comment by glima** [comment]
I see, fair. Will wait for the other fix avenue, then, no biggie.

**Review by squirrelsc — APPROVED** [review]

**Pull request merged**
