### PR TITLE
Change data disk sku from Premium_LRS to Standard_LRS

### PR DESCRIPTION
**Pull request by yuxisun1217**
Signed-off-by: Yuxin Sun <yuxisun@redhat.com>

If overwrite VM size with premium unsupported sizes(like Standard_D1_v2) this case will be failed due to "[ERROR] Requested operation cannot be performed because the VM size Standard_D1_v2 does not support the storage account type Premium_LRS of disk 'disk1'."
So please consider to change it to Standard_LRS to support all VM sizes.
Thanks!

### CODE REVIEW

**Comment by juhlee-microsoft** [comment]
@LiliDeng Can you check out again? I see the old test log with Standard_F32s_v2 size, and passed the result. Also the pipeline select Standard storage account by default. I wonder if it is a matter of subscription scope or pipeline default value, as we have missed it.

Log:
StorageAccount = ExistingStorage_Standard

**Comment by LiliDeng** [comment]
> @LiliDeng Can you check out again? I see the old test log with Standard_F32s_v2 size, and passed the result. Also the pipeline select Standard storage account by default. I wonder if it is a matter of subscription scope or pipeline default value, as we have missed it.
> Log:
> StorageAccount = ExistingStorage_Standard

This setting is for OS disk type, here she fixed is data disk types, our default size allows attached SSD data disk, when users override the size, maybe that size doesn't allow to attached SSD type, @yuxisun1217 I suggest to add a replaceable parameter like https://github.com/LIS/LISAv2/blob/master/XML/TestCases/FunctionalTests-DPDK.xml#L11, it has a default value here https://github.com/LIS/LISAv2/blob/master/XML/Other/ReplaceableTestParameters.xml#L41, but we can override it when run .\Run-LisaV2.ps1 pass -CustomTestParameters "DPDK_SOURCE_URL=(otherurl)", it is more flexible, thoughts? Since we don't have a interface to tell you which size allows you to attach SSD, which doesn't.

**Comment by yuxisun1217** [comment]
Thanks @LiliDeng ! I'll submit another patch to use parameter then.

**Review by juhlee-microsoft — APPROVED** [review]
It looks good. Do you have change test result?

**Comment by juhlee-microsoft** [comment]
@yuxisun1217 Can you share the change base test result with me? It would be nice before my final sign-off.

**Comment by yuxisun1217** [comment]
Hi @juhlee-microsoft,
Sorry the test result is removed. I'll rerun a test and send you test result later. Thanks!

**Comment by yuxisun1217** [comment]
Hi @juhlee-microsoft ,

https://github.com/yuxisun1217/temp
The 4 logs for 4 cases:
.\Run-LisaV2.ps1 -XMLSecretFile .\secret.xml -ParametersFile .\TestParameters.xml -OverrideVMSize Standard_D1_v2 -TestNames STORAGE-HOT-ADD-DISK-SERIAL -CustomTestParameters "DATA_DISK_SKU=Standard_LRS"
.\Run-LisaV2.ps1 -XMLSecretFile .\secret.xml -ParametersFile .\TestParameters.xml -OverrideVMSize Standard_DS1_v2 -TestNames STORAGE-HOT-ADD-DISK-SERIAL
.\Run-LisaV2.ps1 -XMLSecretFile .\secret.xml -ParametersFile .\TestParameters.xml -OverrideVMSize Standard_D1_v2 -TestNames STORAGE-HOT-ADD-DISK-PARALLEL -CustomTestParameters "DATA_DISK_SKU=Standard_LRS"
.\Run-LisaV2.ps1 -XMLSecretFile .\secret.xml -ParametersFile .\TestParameters.xml -OverrideVMSize Standard_DS1_v2 -TestNames STORAGE-HOT-ADD-DISK-PARALLEL

Thanks!

**Pull request merged**
