### PR TITLE
Add custom timeout parameter in Install-CustomScript.ps1

### PR DESCRIPTION
**Pull request by lubaihua33**
Signed-off-by: Baihua Lu <balu@microsoft.com>

### CODE REVIEW

**Comment by lubaihua33** [comment]
When running a command on the VM over the default time 360s, the Wait-Job will stop. Add a timeout parameter so that users can specify the time.

Before fix:
After fix:
`PS E:\Baihua\LISAv2> .\Utilities\Install-CustomScript.ps1 -AzureSecretsFile E:\Baihua\AzureSecretsTestOnly.xml -VmName $vmName `
-ResourceGroupName "$($rg.ResourceGroupName)" `
-FileUris "https://lisawestus2.blob.core.windows.net/testcontainer/build-kernel-4.9-with-HyperV-Backports.sh" `
-CommandToRun "bash build-kernel-4.9-with-HyperV-Backports.sh" -Timeout 3000 -StorageAccountName "lisawestus2" `
-StorageAccountKey "rXFpNm3xbhF5aVBoxJzndXET+iJu9M05evkSnxSYyTI/J89kahFjC5jzkp4SMmfyzEw9m6Aefo+pnXgTMA4u6A==" `
-OSType Linux
11/04/2019 10:47:43 : [INFO ] Secrets file found.
11/04/2019 10:47:43 : [INFO ] Using provided secrets file: E:\Baihua\AzureSecretsTestOnly.xml
11/04/2019 10:47:43 : [INFO ] E:\Baihua\AzureSecretsTestOnly.xml found.
11/04/2019 10:47:43 : [INFO ] ------------------------------------------------------------------
11/04/2019 10:47:43 : [INFO ] Authenticating Azure PS session using Service Principal...
11/04/2019 10:47:44 : [INFO ] Current Subscription : 0cc2a67a-xxxx-xxxx-xxxx-bfa46a28e896.
11/04/2019 10:47:44 : [INFO ] ------------------------------------------------------------------

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command                  
--     ----            -------------   -----         -----------     --------             -------                  
39     Long Running... AzureLongRun... Completed     True            localhost            Set-AzVMExtension        
11/04/2019 11:24:24 : [INFO ] Installation on VM lbh-1889569201 in resource group LISAv2-Deploy1VM-lbh-1889569201-KV18-20191104023013: Completed
11/04/2019 11:24:24 : [INFO ] CustomScript extension is newly installed on 1 VMs among 1 Linux VMs in the subscription
`

**Comment by lubaihua33** [comment]
`asdfsdf`

**Comment by lubaihua33** [comment]
c_afasdfsdfgsdfgsdg_

**Comment by lubaihua33** [comment]
When running a command on the VM over the default time 360s, the Wait-Job will stop. Add a timeout parameter so that users can specify the time.
Before fix:
After fix:

`
PS E:\Baihua\LISAv2> .\Utilities\Install-CustomScript.ps1 -AzureSecretsFile E:\Baihua\AzureSecretsTestOnly.xml -VmName $vmName `
-ResourceGroupName "$($rg.ResourceGroupName)" `
-FileUris "https://lisawestus2.blob.core.windows.net/testcontainer/build-kernel-4.9-with-HyperV-Backports.sh" `
-CommandToRun "bash build-kernel-4.9-with-HyperV-Backports.sh" -Timeout 3000 -StorageAccountName "lisawestus2" `
-StorageAccountKey "rXFpNm3xbhF5aVBoxJzndXET+iJu9M05evkSnxSYyTI/J89kahFjC5jzkp4SMmfyzEw9m6Aefo+pnXgTMA4u6A==" `
-OSType Linux
11/04/2019 10:47:43 : [INFO ] Secrets file found.
11/04/2019 10:47:43 : [INFO ] Using provided secrets file: E:\Baihua\AzureSecretsTestOnly.xml
11/04/2019 10:47:43 : [INFO ] E:\Baihua\AzureSecretsTestOnly.xml found.
11/04/2019 10:47:43 : [INFO ] ------------------------------------------------------------------
11/04/2019 10:47:43 : [INFO ] Authenticating Azure PS session using Service Principal...
11/04/2019 10:47:44 : [INFO ] Current Subscription : 0cc2a67a-xxxx-xxxx-xxxx-bfa46a28e896.
11/04/2019 10:47:44 : [INFO ] ------------------------------------------------------------------

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command                  
--     ----            -------------   -----         -----------     --------             -------                  
39     Long Running... AzureLongRun... Completed     True            localhost            Set-AzVMExtension        
11/04/2019 11:24:24 : [INFO ] Installation on VM lbh-1889569201 in resource group LISAv2-Deploy1VM-lbh-1889569201-KV18-20191104023013: Completed
11/04/2019 11:24:24 : [INFO ] CustomScript extension is newly installed on 1 VMs among 1 Linux VMs in the subscription
`

**Comment by lubaihua33** [comment]
When running a command on VM over the default time 360s, Wait-Job will stop. Add a timeout parameter so that users can specify the time.

**Comment by juhlee-microsoft** [comment]
> When running a command on VM over the default time 360s, Wait-Job will stop. Add a timeout parameter so that users can specify the time.

@lubaihua33 Please post the test log in plain text here not the link or attached file. They look short so they should be fine.

**Review by juhlee-microsoft — APPROVED** [review]

**Comment by lubaihua33** [comment]
Before fix:
```
PS E:\Baihua\LISAv2> .\Utilities\Install-CustomScript.ps1 -AzureSecretsFile E:\Baihua\AzureSecretsTestOnly.xml -VmName $vmName `
-ResourceGroupName "$($rg.ResourceGroupName)" `
-FileUris "https://XXX.blob.core.windows.net/build.sh" `
-CommandToRun "bash build.sh" -StorageAccountName "" `
-StorageAccountKey "" `
-OSType Linux
11/04/2019 11:26:04 : [INFO ] Secrets file found.
11/04/2019 11:26:04 : [INFO ] Using provided secrets file: E:\Baihua\AzureSecretsTestOnly.xml
11/04/2019 11:26:04 : [INFO ] E:\Baihua\AzureSecretsTestOnly.xml found.
11/04/2019 11:26:04 : [INFO ] ------------------------------------------------------------------
11/04/2019 11:26:04 : [INFO ] Authenticating Azure PS session using Service Principal...
11/04/2019 11:26:06 : [INFO ] Current Subscription : 0cc2a67a-xxxx-xxxx-xxxx-bfa46a28e896.
11/04/2019 11:26:06 : [INFO ] ------------------------------------------------------------------
11/04/2019 11:32:08 : [INFO ] Installation on VM lbh-1125518160 in resource group LISAv2-Deploy1VM-lbh-1125518160-YV88-20191104031849: Timeout
11/04/2019 11:32:08 : [INFO ] CustomScript extension is newly installed on 1 VMs among 1 Linux VMs in the subscription

11/04/2019 11:32:08 : [WARN ] CustomScript extension is failed on 1 Linux VMs

11/04/2019 11:32:08 : [INFO ] - VM lbh-1125518160 in resource group LISAv2-Deploy1VM-lbh-1125518160-YV88-20191104031849
```

After fix:
```
PS E:\Baihua\LISAv2> .\Utilities\Install-CustomScript.ps1 -AzureSecretsFile E:\Baihua\AzureSecretsTestOnly.xml -VmName $vmName `
-ResourceGroupName "$($rg.ResourceGroupName)" `
-FileUris "https://XXX.blob.core.windows.net/build.sh" `
-CommandToRun "bash build.sh" -Timeout 3000 -StorageAccountName "" `
-StorageAccountKey "" `
-OSType Linux
11/04/2019 11:39:18 : [INFO ] Secrets file found.
11/04/2019 11:39:18 : [INFO ] Using provided secrets file: E:\Baihua\AzureSecretsTestOnly.xml
11/04/2019 11:39:18 : [INFO ] E:\Baihua\AzureSecretsTestOnly.xml found.
11/04/2019 11:39:18 : [INFO ] ------------------------------------------------------------------
11/04/2019 11:39:18 : [INFO ] Authenticating Azure PS session using Service Principal...
11/04/2019 11:39:20 : [INFO ] Current Subscription : 0cc2a67a-xxxx-xxxx-xxxx-bfa46a28e896.
11/04/2019 11:39:20 : [INFO ] ------------------------------------------------------------------

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command                  
--     ----            -------------   -----         -----------     --------             -------                  
78     Long Running... AzureLongRun... Completed     True            localhost            Set-AzVMExtension        
11/04/2019 12:12:58 : [INFO ] Installation on VM lbh-1099099979 in resource group LISAv2-Deploy1VM-lbh-1099099979-ZP46-20191104033354: Completed
11/04/2019 12:12:58 : [INFO ] CustomScript extension is newly installed on 1 VMs among 1 Linux VMs in the subscription
```

**Pull request merged**
