### PR TITLE
Add ignorable logs

### PR DESCRIPTION
**Pull request by yuxisun1217**
After testing these days, I think these error/fail/warning messages should be ignored:

May  6 00:06:10 localhost kdumpctl[1000]: Warning: There might not be enough space to save a vmcore.
May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
May  6 00:16:11 localhost dnf[7457]: Failed determining last makecache time.

Thanks!

### CODE REVIEW

**Comment by yuxisun1217** [comment]
Because it's hard to hit all of these messages in one run, I test it by adding these messages in /var/log/messages manually and run VERIFY-BOOT-ERROR-WARNINGS.py manually.

Test log: https://github.com/yuxisun1217/temp/blob/master/Runtime.log

**Comment by LiliDeng** [comment]
@yuxisun1217 Thanks, do you have any comments for what's the reason/root cause for the warning/failure.

**Comment by yuxisun1217** [comment]
Hi @LiliDeng ,

- **Failed determining last makecache time.**
I think it because there's no enabled repo in my VM:
```
May  8 12:32:47 localhost dnf[11283]: Failed determining last makecache time.
May  8 12:32:47 localhost dnf[11283]: There are no enabled repos.
```

- **Warning: There might not be enough space to save a vmcore**
I think it because my OS disk size is small(10G)
```
May  7 09:39:51 localhost kdumpctl: Warning: There might not be enough space to save a vmcore.
May  7 09:39:51 localhost kdumpctl: The size of /dev/sda4 should be greater than 7892928 kilo bytes.
# df -h
/dev/sda4       8.8G  2.2G  6.2G  26% /
```

- **NetworkManager[2930]: [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known**
Actually I have no idea why this happened. I rerun this case in the same VM size and os vhd but cannot see this log again. I guess it was generated in the previous cases. 
We can consider not to ignore this message now until we make it clear.

**Comment by yuxisun1217** [comment]
Hi @LiliDeng ,
I removed the "dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known" from ignorable message. Now only two new messages left:
```
May 6 00:06:10 localhost kdumpctl[1000]: Warning: There might not be enough space to save a vmcore.
May 6 00:16:11 localhost dnf[7457]: Failed determining last makecache time.
```

**Comment by LiliDeng** [comment]
@yuxisun1217 Thanks, merged.

**Review by LiliDeng — APPROVED** [review]

**Pull request merged**
