### PR TITLE
Fix issue when VM not existed + -UseExistingRG use.

### PR DESCRIPTION
**Pull request by LiliDeng**
There is a bug when using -UseExistingRG, and no VM existed in current RG.
$ExistingRG => $UseExistingRG is to fix this issue.
```
Exception before fix - 
New-AzureRmResourceGroupDeployment : 1:34:02 AM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The resource 
'Microsoft.Compute/availabilitySets/AvailabilitySet' is not defined in the template.
```
After this issue fixed, deployment success with a new public IP created, but in our code, we collected all IPs info in current RG. I fixed it by only collect IP which assigned address which means it is associated with other resource (LB or VM).

I already did basic testing, will do more testing, and let know your thoughts. @lizzha

### CODE REVIEW

**Comment by ader1990** [comment]
this is a duplicate of my fix: https://github.com/LIS/LISAv2/pull/30

**Comment by ader1990** [comment]
@LiliDeng can you add the code from my PR to this PR and test with the merged code?

**Review by ader1990 — CHANGES_REQUESTED** [review]
Please merge #30 code with this PR, as they fix the same thing.

**Comment by LiliDeng** [comment]
Scenario 1
Run a case in a normal usage - Pass

Scenario 2
Run a case without cleanup - PASS
Run a case against above RG again without keep, it will delete resources under this RG except for availability set - Pass
Now RG only has one availability set, manual delete it, run case using an empty RG - Pass

Scenario 3
Run a case without cleanup - PASS
Manual delete VM, run case against this RG - PASS (here it will create a new public ip)

Scenario 4
Run a case without cleanup - PASS
Run a case against above RG without keep, it will delete resources under this RG except for availability set - Pass
Run a case using above RG with only one availability set - Pass

**Review by lizzha — APPROVED** [review]

**Review by ader1990 — APPROVED** [review]

**Comment by ader1990** [comment]
thank you @LiliDeng. Can I remove my old PR now?

**Review by juhlee-microsoft — APPROVED** [review]

**Comment by juhlee-microsoft** [comment]
@ader1990 please remove your PR safely.

**Pull request merged**
