### PR TITLE
dpdk: fix for testpmd new incompatibility

### LINKED ISSUE #305: DPDK: fix VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC for DPDK master
In file included from /root/dpdk-next-net/app/test-pmd/macfwd.c:30:0:
/root/dpdk-next-net/app/test-pmd/macfwd.c: In function ‘pkt_burst_mac_forward’:
/root/dpdk-next-net/app/test-pmd/macfwd.c:101:66: error: invalid application of ‘sizeof’ to incomplete type ‘struct ether_hdr’
 ipv4_hdr = rte_pktmbuf_mtod_offset(mb, struct ipv4_hdr *, sizeof(struct ether_hdr)); ipv4_hdr->dst_addr = rte_be_to_cpu_32(IPv4(10,0,1,4));
                                                                  ^
/root/dpdk-next-net/build/include/rte_mbuf.h:2023:48: note: in definition of macro ‘rte_pktmbuf_mtod_offset’
  ((t)((char *)(m)->buf_addr + (m)->data_off + (o)))
                                                ^
/root/dpdk-next-net/app/test-pmd/macfwd.c:101:94: error: dereferencing pointer to incomplete type ‘struct ipv4_hdr’
 ipv4_hdr = rte_pktmbuf_mtod_offset(mb, struct ipv4_hdr *, sizeof(struct ether_hdr)); ipv4_hdr->dst_addr = rte_be_to_cpu_32(IPv4(10,0,1,4));
                                                                                              ^~
In file included from /root/dpdk-next-net/app/test-pmd/macfwd.c:17:0:
/root/dpdk-next-net/app/test-pmd/macfwd.c:101:124: error: implicit declaration of function ‘IPv4’ [-Werror=implicit-function-declaration]
 ipv4_hdr = rte_pktmbuf_mtod_offset(mb, struct ipv4_hdr *, sizeof(struct ether_hdr)); ipv4_hdr->dst_addr = rte_be_to_cpu_32(IPv4(10,0,1,4));
                                                                                                                            ^
/root/dpdk-next-net/build/include/rte_byteorder.h:55:57: note: in definition of macro ‘rte_bswap32’
 #define rte_bswap32(x) ((uint32_t)(__builtin_constant_p(x) ?  \
                                                         ^
/root/dpdk-next-net/app/test-pmd/macfwd.c:101:107: note: in expansion of macro ‘rte_be_to_cpu_32’
 ipv4_hdr = rte_pktmbuf_mtod_offset(mb, struct ipv4_hdr *, sizeof(struct ether_hdr)); ipv4_hdr->dst_addr = rte_be_to_cpu_32(IPv4(10,0,1,4));
                                                                                                           ^~~~~~~~~~~~~~~~
/root/dpdk-next-net/app/test-pmd/macfwd.c:101:124: error: nested extern declaration of ‘IPv4’ [-Werror=nested-externs]
 ipv4_hdr = rte_pktmbuf_mtod_offset(mb, struct ipv4_hdr *, sizeof(struct ether_hdr)); ipv4_hdr->dst_addr = rte_be_to_cpu_32(IPv4(10,0,1,4));
                                                                                                                            ^
/root/dpdk-next-net/build/include/rte_byteorder.h:55:57: note: in definition of macro ‘rte_bswap32’
 #define rte_bswap32(x) ((uint32_t)(__builtin_constant_p(x) ?  \
                                                         ^
/root/dpdk-next-net/app/test-pmd/macfwd.c:101:107: note: in expansion of macro ‘rte_be_to_cpu_32’
 ipv4_hdr = rte_pktmbuf_mtod_offset(mb, struct ipv4_hdr *, sizeof(struct ether_hdr)); ipv4_hdr->dst_addr = rte_be_to_cpu_32(IPv4(10,0,1,4));
                                                                                                           ^~~~~~~~~~~~~~~~
/root/dpdk-next-net/app/test-pmd/macfwd.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-address-of-packed-member’ [-Werror]
cc1: all warnings being treated as errors
/root/dpdk-next-net/mk/internal/rte.compile-pre.mk:114: recipe for target 'macfwd.o' failed
make[3]: *** [macfwd.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  LD testpipeline

### PR DESCRIPTION
**Pull request by ader1990**
Fixes https://github.com/LIS/LISAv2/issues/305

test-pmd/macfwd.c has been changed in DPDK v19.08 and it s breaking the automation code.
This fixes the problem for DPDK versions >= 19.08 and keeps the automation okay for previous versions.

### CODE REVIEW

**Comment by juhlee-microsoft** [comment]
@ader1990 any chance you can post the result? The code change looks ok to me.

**Comment by juhlee-microsoft** [comment]
> @ader1990 any chance you can post the result? The code change looks ok to me.

have you tested and proved the result?

**Comment by ader1990** [comment]
@juhlee-microsoft work still in progress

**Comment by juhlee-microsoft** [comment]
> @juhlee-microsoft work still in progress

ok, I put 'pr-under-test' label until it is ready.

**Comment by ader1990** [comment]
will reopen for fix once the DPDK code stabilizes.

**Review by chvalean — APPROVED** [review]

**Pull request merged**
