### PR TITLE
skip case when preview feature is not enabled

### PR DESCRIPTION
**Pull request by LiliDeng**

### CODE REVIEW

**Comment by LiliDeng** [comment]
@squirrelsc there is one concern that, whether the original exception is HttpResponseError type.

**Comment by squirrelsc** [comment]
> @squirrelsc there is one concern that, whether the original exception is HttpResponseError type.

Did you have a chance to repro it? How about the validation service subscription?

**Review by squirrelsc — APPROVED** [review]

**Comment by LiliDeng** [comment]
> > @squirrelsc there is one concern that, whether the original exception is HttpResponseError type.
> 
> Did you have a chance to repro it? How about the validation service subscription?

I have tried with dev and test, but unregister the feature doesn't take effect, let me try with your suggestion. thanks.

**Comment by LiliDeng** [comment]
> > @squirrelsc there is one concern that, whether the original exception is HttpResponseError type.
> 
> Did you have a chance to repro it? How about the validation service subscription?

I have tested it.

**Pull request merged**
