### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by juhlee-microsoft**
Found new binaries in the Tools

### CODE REVIEW

**Comment by LiliDeng** [comment]
Any places we used them in our testing?

**Comment by juhlee-microsoft** [comment]
> Any places we used them in our testing?

Binaries?

**Comment by LiliDeng** [comment]
> Any places we used them in our testing?
> 
> Binaries?

New added ones.

**Comment by juhlee-microsoft** [comment]
PERF-GOLANG-BENCHMARK used 2 tarball files. 
SSTRESSTEST-WEB-PARALLEL-ACCESS used 1 http tarball file
nc64 is 64bit version of nc.exe
I think it is ok to add them, @LiliDeng

**Review by LiliDeng — APPROVED** [review]

**Pull request merged**
