### PR TITLE
Merge Install_Dpdk function to dpdkUtils.sh

### LINKED ISSUE #63: Cleanup duplicate DPDK install code in the dpdkSetup.sh and dpdkUtils.sh
The code from dpdkSetup.sh and dpdkUtils.sh should be unified and duplicates removed.

### PR DESCRIPTION
**Pull request by v-sijliu**
fix #63 
Test results:
```
[LISAv2 Test Results Summary]
Test Run On           : 07/30/2019 07:20:55
ARM Image Under Test  : canonical : ubuntuserver : 16.04-lts : Latest
Initial Kernel Version: 4.15.0-1052-azure
Final Kernel Version  : 4.15.0-1052-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:29

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC                                               PASS                22.15 
dpdk_version test_mode phase   fwdrx_pps_avg fwdtx_pps_avg
------------ --------- -----   ------------- -------------
18.11.0      txonly    after   3387019       3387019      
18.11.0      txonly    before  3355010       3355010      
18.11.0      txonly    during  142600        142600       
18.11.0      txonly    overall 2044287       2044287 
```
```
[LISAv2 Test Results Summary]
Test Run On           : 07/30/2019 07:21:11
ARM Image Under Test  : canonical : ubuntuserver : 16.04-lts : Latest
Initial Kernel Version: 4.15.0-1052-azure
Final Kernel Version  : 4.15.0-1052-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:10

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-COMPLIANCE                                                            PASS                 5.88 
```
```
[LISAv2 Test Results Summary]
Test Run On           : 07/30/2019 07:49:02
ARM Image Under Test  : canonical : ubuntuserver : 16.04-lts : Latest
Initial Kernel Version: 4.15.0-1052-azure
Final Kernel Version  : 4.15.0-1052-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:28

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-BUILD-AND-TESTPMD-TEST                                                PASS                21.89 
```
```
[LISAv2 Test Results Summary]
Test Run On           : 07/30/2019 07:50:23
ARM Image Under Test  : canonical : ubuntuserver : 16.04-lts : Latest
Initial Kernel Version: 4.15.0-1052-azure
Final Kernel Version  : 4.15.0-1052-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:21

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-VPP                                                                   PASS                16.82 
```

### CODE REVIEW

**Comment by ader1990** [comment]
The code looks good at a first glance, thanks for the change.

We need a full DPDK run for this change though, including the DPDK community tests.

**Comment by LiliDeng** [comment]
@v-sijliu Found some cases abort on 18.04, please double check.

**Comment by v-sijliu** [comment]
VERIFY-DPDK-NFF-GO  and VERIFY-DPDK-OVS abort also abort on master.
```
[LISAv2 Test Results Summary]
Test Run On           : 07/31/2019 03:08:29
ARM Image Under Test  : canonical : ubuntuserver : 16.04-lts : Latest
Test Category         : Functional
Test Area             : DPDK
Initial Kernel Version: 4.15.0-1052-azure
Final Kernel Version  : 4.15.0-1052-azure
Total Test Cases      : 9 (6 Passed, 0 Failed, 2 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:2:56

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-NFF-GO                                                             ABORTED                12.13 
    2 DPDK                 VERIFY-DPDK-VPP                                                                   PASS                17.76 
    3 DPDK                 VERIFY-DPDK-PRIMARY-SECONDARY-PROCESSES                                        SKIPPED                 1.76 
    4 DPDK                 VERIFY-DPDK-OVS                                                                ABORTED                15.89 
    5 DPDK                 VERIFY-DPDK-BUILD-AND-TESTPMD-TEST                                                PASS                21.88 
    6 DPDK                 VERIFY-SRIOV-FAILSAFE-FOR-DPDK                                                    PASS                36.97 
	DPDK-TESTPMD : Initial SRIOV : DPDK 18.11.0 : TxPPS : 12793825 : RxPPS : 12621930 
	DPDK-TESTPMD : Synthetic : DPDK 18.11.0 : TxPPS : 491812 : RxPPS : 77885 
	DPDK-TESTPMD : Re-Enable SRIOV : DPDK 18.11.0 : TxPps : 14517708 : RxPps : 14502008 
	DPDK RxPPS : Difference between Initial and Re-Enabled SRIOV : 12621930 : 14502008 : 14.9 % 
    7 DPDK                 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC                                               PASS                22.59 
dpdk_version test_mode phase   fwdrx_pps_avg fwdtx_pps_avg
------------ --------- -----   ------------- -------------
18.11.0      txonly    after   3295311       3295311      
18.11.0      txonly    before  3257745       3257745      
18.11.0      txonly    during  258783        258783       
18.11.0      txonly    overall 2351621       2351621 
    8 DPDK                 VERIFY-DPDK-COMPLIANCE                                                            PASS                 6.91 
    9 DPDK                 VERIFY-DPDK-RING-LATENCY                                                          PASS                 8.33 
```
```
[LISAv2 Test Results Summary]
Test Run On           : 07/31/2019 03:08:20
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Test Category         : Functional
Test Area             : DPDK
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1024-azure
Total Test Cases      : 9 (7 Passed, 0 Failed, 1 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:3:7

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-NFF-GO                                                                PASS                13.02 
    2 DPDK                 VERIFY-DPDK-VPP                                                                   PASS                18.97 
    3 DPDK                 VERIFY-DPDK-PRIMARY-SECONDARY-PROCESSES                                        SKIPPED                 2.13 
    4 DPDK                 VERIFY-DPDK-OVS                                                                ABORTED                18.33 
    5 DPDK                 VERIFY-DPDK-BUILD-AND-TESTPMD-TEST                                                PASS                22.75 
    6 DPDK                 VERIFY-SRIOV-FAILSAFE-FOR-DPDK                                                    PASS                44.55 
	DPDK-TESTPMD : Initial SRIOV : DPDK 18.11.0 : TxPPS : 11325735 : RxPPS : 11322049 
	DPDK-TESTPMD : Synthetic : DPDK 18.11.0 : TxPPS : 458642 : RxPPS : 0 
	DPDK-TESTPMD : Re-Enable SRIOV : DPDK 18.11.0 : TxPps : 11817699 : RxPps : 11802187 
	DPDK RxPPS : Difference between Initial and Re-Enabled SRIOV : 11322049 : 11802187 : 4.24 % 
    7 DPDK                 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC                                               PASS                23.54 
dpdk_version test_mode phase   fwdrx_pps_avg fwdtx_pps_avg
------------ --------- -----   ------------- -------------
18.11.0      txonly    after   3325220       3325220      
18.11.0      txonly    before  3239237       3239237      
18.11.0      txonly    during  407514        407513       
18.11.0      txonly    overall 2066003       2066003 
    8 DPDK                 VERIFY-DPDK-COMPLIANCE                                                            PASS                 7.58 
    9 DPDK                 VERIFY-DPDK-RING-LATENCY                                                          PASS                 8.83 
```

**Comment by ader1990** [comment]
@v-sijliu the ovs master is supposed to fail with the stable 18.11 DPDK
On the NFF-GO part, you need to rerun/check the logs.

**Review by ader1990 — APPROVED** [review]

**Comment by LiliDeng** [comment]
@v-sijliu I‘d like some testing on all supported distro, to make sure not break things.

**Comment by LiliDeng** [comment]
Hit issue during testing, will send out new one once pass on all dpdk tests + supported distro

**Pull request closed without merging**
