### PR TITLE
Fix NET-BOOT-NONIC-HOT-ADD-NIC test case issue and remove redundant invoke of Detect-LinuxDistro

### PR DESCRIPTION
**Pull request by Tong-Xu**
Fix case NET-BOOT-NONIC-HOT-ADD-NIC and refine usage of Detect-LinuxDistro 
Test results:
```
[LISAv2 Test Results Summary]
Test Run On           : 07/22/2019 09:49:17
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1024-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:9

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 VERIFY-VHD-PREREQUISITES                                                          PASS                 4.65 

[LISAv2 Test Results Summary]
Test Run On           : 07/22/2019 09:50:06
VHD Under Test        : C:\tx\tx-ubuntu1804-gen2.vhdx
Initial Kernel Version: 4.15.0-54-generic
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:20

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NETWORK              NET-BOOT-NONIC-HOT-ADD-NIC                                                        PASS                17.38 

[LISAv2 Test Results Summary]
Test Run On           : 07/22/2019 09:52:36
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1024-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:24

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 STRESS               STRESSTEST-WEB-PARALLEL-ACCESS                                                    PASS                 16.5 

[LISAv2 Test Results Summary]
Test Run On           : 07/22/2019 09:46:06
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Initial Kernel Version: 4.18.0-1024-azure
Final Kernel Version  : 4.18.0-1024-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:47

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 GPU                  NVIDIA-GRID-DRIVER-TENSORFLOW                                                     PASS                40.69 
```

### CODE REVIEW

**Review by juhlee-microsoft — COMMENTED** [review]
@Tong-Xu have you checked all other lines in the same script if there is 'linuxRelease' variable? You literally removed this variable in some of files. We should make sure if there is missing update a.k.a. undefined variable.

**Comment by LiliDeng** [comment]
@Tong-Xu Please double check for Ju's comments.

**Comment by Tong-Xu** [comment]
I have double checked all other lines in the same script , there isn't  'linuxRelease' variable. @juhlee-microsoft

**Comment by chvalean** [comment]
Title of the PR is misleading.

Please add that call for DetectDistro  condition only for the targeted test case, where it is understood that at first boot there would be no NIC.

**Review by chvalean — CHANGES_REQUESTED** [review]
Please add that call for DetectDistro condition only for the targeted test case, where it is understood that at first boot there would be no NIC.

For the other tests changed, $global:detectedDistro is successfully used in other scripts already, why add an additional condition for it?

**Comment by LiliDeng** [comment]
@Tong-Xu Please paste test result for NET-BOOT-NONIC-HOT-ADD-NIC against latest code.

**Comment by Tong-Xu** [comment]
Test results:
```
[LISAv2 Test Results Summary]
Test Run On           : 07/22/2019 09:50:06
VHD Under Test        : C:\tx\tx-ubuntu1804-gen2.vhdx
Initial Kernel Version: 4.15.0-54-generic
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:20

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NETWORK              NET-BOOT-NONIC-HOT-ADD-NIC                                                        PASS                17.38 
```

**Review by juhlee-microsoft — APPROVED** [review]

**Pull request merged**
