### PR TITLE
Use built-in WALA agent

### PR DESCRIPTION
**Pull request by juhlee-microsoft**
Use the latest WALA agent in the system as it has the fix of RDMA.
Clean up Ubuntu support filter.  (Still working on the Ubuntu 16.04 enablement)

### CODE REVIEW

**Comment by juhlee-microsoft** [comment]
### **Open MPI result**

[LISAv2 Test Results Summary]
Test Run On           : 09/06/2019 16:04:39
ARM Image Under Test  : **Redhat : RHEL : 7.6 : latest**
Initial Kernel Version: 3.10.0-957.21.3.el7.x86_64
Final Kernel Version  : 3.10.0-957.21.3.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:31

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 INFINIBAND           INFINIBAND-OPEN-MPI-2VM                                                           PASS                24.96
        InfiniBand-Verification-1-FirstBoot : eth0 IP : PASS
        InfiniBand-Verification-1-FirstBoot : IBV_PINGPONG : PASS
        InfiniBand-Verification-1-FirstBoot : PingPong Intranode : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-MPI1 : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-P2P : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-NBC : PASS
        InfiniBand-Verification-2-Reboot : eth0 IP : PASS
        InfiniBand-Verification-2-Reboot : IBV_PINGPONG : PASS
        InfiniBand-Verification-2-Reboot : PingPong Intranode : PASS
        InfiniBand-Verification-2-Reboot : IMB-MPI1 : PASS
        InfiniBand-Verification-2-Reboot : IMB-P2P : PASS
        InfiniBand-Verification-2-Reboot : IMB-NBC : PASS


Logs can be found at C:\LISAv2\BG15\TestResults\2019-06-09-09-04-12-7218


09/06/2019 16:36:16 : [INFO ] Creating 'C:\LISAv2\BG15\Azure-BG15-TestLogs.zip' from 'C:\LISAv2\BG15\TestResults\2019-06-09-09-04-12-7218'
09/06/2019 16:36:16 : [INFO ] C:\LISAv2\BG15\Azure-BG15-TestLogs.zip created successfully.
09/06/2019 16:36:16 : [INFO ] Analyzing results..
09/06/2019 16:36:16 : [INFO ] Copying all files back to original working directory: C:\Users\juhlee\source\repo\LIS\LISAv2.
09/06/2019 16:36:20 : [INFO ] Cleaning up C:\LISAv2\BG15
09/06/2019 16:36:21 : [INFO ] Setting workspace back to original location: C:\Users\juhlee\source\repo\LIS\LISAv2
09/06/2019 16:36:21 : [INFO ] LISAv2 exit code: 0


[LISAv2 Test Results Summary]
Test Run On           : 09/06/2019 22:45:36
ARM Image Under Test  : **Canonical : UbuntuServer : 18.04-LTS : latest**
Initial Kernel Version: 5.0.0-1018-azure
Final Kernel Version  : 5.0.0-1018-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:25

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 INFINIBAND           INFINIBAND-OPEN-MPI-2VM                                                           PASS                21.64
        InfiniBand-Verification-1-FirstBoot : eth0 IP : PASS
        InfiniBand-Verification-1-FirstBoot : IBV_PINGPONG : PASS
        InfiniBand-Verification-1-FirstBoot : PingPong Intranode : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-MPI1 : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-P2P : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-NBC : PASS
        InfiniBand-Verification-2-Reboot : eth0 IP : PASS
        InfiniBand-Verification-2-Reboot : IBV_PINGPONG : PASS
        InfiniBand-Verification-2-Reboot : PingPong Intranode : PASS
        InfiniBand-Verification-2-Reboot : IMB-MPI1 : PASS
        InfiniBand-Verification-2-Reboot : IMB-P2P : PASS
        InfiniBand-Verification-2-Reboot : IMB-NBC : PASS


Logs can be found at C:\LISAv2\QC14\TestResults\2019-06-09-15-45-32-1186


09/06/2019 23:10:59 : [INFO ] Creating 'C:\LISAv2\QC14\Azure-QC14-TestLogs.zip' from 'C:\LISAv2\QC14\TestResults\2019-06-09-15-45-32-1186'
09/06/2019 23:10:59 : [INFO ] C:\LISAv2\QC14\Azure-QC14-TestLogs.zip created successfully.
09/06/2019 23:10:59 : [INFO ] Analyzing results..
09/06/2019 23:10:59 : [INFO ] Copying all files back to original working directory: C:\Users\juhlee\source\repo\LIS\LISAv2.
09/06/2019 23:11:03 : [INFO ] Cleaning up C:\LISAv2\QC14
09/06/2019 23:11:03 : [INFO ] Setting workspace back to original location: C:\Users\juhlee\source\repo\LIS\LISAv2
09/06/2019 23:11:03 : [INFO ] LISAv2 exit code: 0


[LISAv2 Test Results Summary]
Test Run On           : 09/09/2019 17:23:57
ARM Image Under Test  : **SUSE : SLES : 12-SP4 : latest**
Initial Kernel Version: 4.12.14-6.23-azure
Final Kernel Version  : 4.12.14-6.23-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:24

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 INFINIBAND           INFINIBAND-OPEN-MPI-2VM                                                           PASS                19.71
        InfiniBand-Verification-1-FirstBoot : eth0 IP : PASS
        InfiniBand-Verification-1-FirstBoot : IBV_PINGPONG : PASS
        InfiniBand-Verification-1-FirstBoot : PingPong Intranode : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-MPI1 : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-P2P : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-NBC : PASS
        InfiniBand-Verification-2-Reboot : eth0 IP : PASS
        InfiniBand-Verification-2-Reboot : IBV_PINGPONG : PASS
        InfiniBand-Verification-2-Reboot : PingPong Intranode : PASS
        InfiniBand-Verification-2-Reboot : IMB-MPI1 : PASS
        InfiniBand-Verification-2-Reboot : IMB-P2P : PASS
        InfiniBand-Verification-2-Reboot : IMB-NBC : PASS


Logs can be found at C:\LISAv2\HZ34\TestResults\2019-09-09-10-23-52-9979


09/09/2019 17:48:10 : [INFO ] Creating 'C:\LISAv2\HZ34\Azure-HZ34-TestLogs.zip' from 'C:\LISAv2\HZ34\TestResults\2019-09-09-10-23-52-9979'
09/09/2019 17:48:10 : [INFO ] C:\LISAv2\HZ34\Azure-HZ34-TestLogs.zip created successfully.
09/09/2019 17:48:10 : [INFO ] Analyzing results..
09/09/2019 17:48:10 : [INFO ] Copying all files back to original working directory: C:\Users\juhlee\source\repo\LIS\LISAv2.
09/09/2019 17:48:14 : [INFO ] Cleaning up C:\LISAv2\HZ34
09/09/2019 17:48:14 : [INFO ] Setting workspace back to original location: C:\Users\juhlee\source\repo\LIS\LISAv2
09/09/2019 17:48:14 : [INFO ] LISAv2 exit code: 0

**Comment by juhlee-microsoft** [comment]
### Intel MPI result

[LISAv2 Test Results Summary]
Test Run On           : 09/05/2019 23:27:00
ARM Image Under Test  : **Redhat : RHEL : 7.6 : latest**
Initial Kernel Version: 3.10.0-957.21.3.el7.x86_64
Final Kernel Version  : 3.10.0-957.21.3.el7.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:5:8

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 INFINIBAND           INFINIBAND-INTEL-MPI-2VM                                                          PASS               304.29
        InfiniBand-Verification-1-FirstBoot : eth0 IP : PASS
        InfiniBand-Verification-1-FirstBoot : IBV_PINGPONG : PASS
        InfiniBand-Verification-1-FirstBoot : PingPong Intranode : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-MPI1 : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-IO : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-RMA : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-NBC : PASS
        InfiniBand-Verification-2-Reboot : eth0 IP : PASS
        InfiniBand-Verification-2-Reboot : IBV_PINGPONG : PASS
        InfiniBand-Verification-2-Reboot : PingPong Intranode : PASS
        InfiniBand-Verification-2-Reboot : IMB-MPI1 : PASS
        InfiniBand-Verification-2-Reboot : IMB-IO : PASS
        InfiniBand-Verification-2-Reboot : IMB-RMA : PASS
        InfiniBand-Verification-2-Reboot : IMB-NBC : PASS


Logs can be found at C:\LISAv2\AV91\TestResults\2019-05-09-16-26-56-1639


09/06/2019 04:35:44 : [INFO ] Creating 'C:\LISAv2\AV91\Azure-AV91-TestLogs.zip' from 'C:\LISAv2\AV91\TestResults\2019-05-09-16-26-56-1639'
09/06/2019 04:35:46 : [INFO ] C:\LISAv2\AV91\Azure-AV91-TestLogs.zip created successfully.
09/06/2019 04:35:46 : [INFO ] Analyzing results..
09/06/2019 04:35:46 : [INFO ] Copying all files back to original working directory: C:\Users\juhlee\source\repo\LIS\LISAv2.
09/06/2019 04:35:50 : [INFO ] Cleaning up C:\LISAv2\AV91
09/06/2019 04:35:50 : [INFO ] Setting workspace back to original location: C:\Users\juhlee\source\repo\LIS\LISAv2
09/06/2019 04:35:50 : [INFO ] LISAv2 exit code: 0

**Comment by juhlee-microsoft** [comment]
### MVAPICH MPI result

[LISAv2 Test Results Summary]
Test Run On           : 09/09/2019 18:42:49
ARM Image Under Test  : **SUSE : SLES : 12-SP4 : latest**
Initial Kernel Version: 4.12.14-6.23-azure
Final Kernel Version  : 4.12.14-6.23-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:4:28

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes)
-------------------------------------------------------------------------------------------------------------------------------------------
    1 INFINIBAND           INFINIBAND-MVAPICH-MPI-2VM                                                        PASS               260.47
        InfiniBand-Verification-1-FirstBoot : eth0 IP : PASS
        InfiniBand-Verification-1-FirstBoot : IBV_PINGPONG : PASS
        InfiniBand-Verification-1-FirstBoot : PingPong Intranode : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-MPI1 : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-P2P : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-IO : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-RMA : PASS
        InfiniBand-Verification-1-FirstBoot : IMB-NBC : PASS
        InfiniBand-Verification-2-Reboot : eth0 IP : PASS
        InfiniBand-Verification-2-Reboot : IBV_PINGPONG : PASS
        InfiniBand-Verification-2-Reboot : PingPong Intranode : PASS
        InfiniBand-Verification-2-Reboot : IMB-MPI1 : PASS
        InfiniBand-Verification-2-Reboot : IMB-P2P : PASS
        InfiniBand-Verification-2-Reboot : IMB-IO : PASS
        InfiniBand-Verification-2-Reboot : IMB-RMA : PASS
        InfiniBand-Verification-2-Reboot : IMB-NBC : PASS


Logs can be found at C:\LISAv2\ZI51\TestResults\2019-09-09-11-42-44-7572


09/09/2019 23:10:59 : [INFO ] Creating 'C:\LISAv2\ZI51\Azure-ZI51-TestLogs.zip' from 'C:\LISAv2\ZI51\TestResults\2019-09-09-11-42-44-7572'
09/09/2019 23:11:01 : [INFO ] C:\LISAv2\ZI51\Azure-ZI51-TestLogs.zip created successfully.
09/09/2019 23:11:01 : [INFO ] Analyzing results..
09/09/2019 23:11:01 : [INFO ] Copying all files back to original working directory: C:\Users\juhlee\source\repo\LIS\LISAv2.
09/09/2019 23:11:05 : [INFO ] Cleaning up C:\LISAv2\ZI51
09/09/2019 23:11:05 : [INFO ] Setting workspace back to original location: C:\Users\juhlee\source\repo\LIS\LISAv2
09/09/2019 23:11:05 : [INFO ] LISAv2 exit code: 0

**Comment by LiliDeng** [comment]
Looks good, I didn't see you clone latest WALA, is it expected? Or it is already the latest in gallery image (or self update?)

**Comment by juhlee-microsoft** [comment]
> Looks good, I didn't see you clone latest WALA, is it expected? Or it is already the latest in gallery image (or self update?)

By default, we should use the latest one or the specific version with Azure image. But sometimes it got broken or need pre-release one for our work. Last time, we pick up the specific commit and that does not need any more. @LiliDeng  Please let me know if there is anything else needs.

**Review by LiliDeng — APPROVED** [review]

**Pull request merged**
