### PR TITLE
support cached results in tools

### PR DESCRIPTION
**Pull request by squirrelsc**

### CODE REVIEW

**Review by glima — COMMENTED** [review]
This is dangerous, isn't it? What about commands like "date"? I see more harm than good here. (Context: first commit)

**Review by glima — COMMENTED** [review]
dmesg should also be fresh clean each invocation, no?

**Comment by squirrelsc** [comment]
> dmesg should also be fresh clean each invocation, no?

It depends on test scenarios, there is a argument to turn it on or off for dmesg. Currently, every test case needs to get system information from dmesg. It calls several times and generates a lot of logs. If in future, it's more common to fresh dmesg, we can switch default value to True.

**Comment by squirrelsc** [comment]
> This is dangerous, isn't it? What about commands like "date"? I see more harm than good here. (Context: first commit)

`date` is hard coded to True in this change. If something doesn't run well, we can find it when developing test cases. Use the lazy run mode by default, which helps improving running time and making a clearer log.

**Pull request merged**
